/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import final_panels.AddMedicine;
import final_panels.AddVendor;
import final_panels.ListMedicines;
import final_panels.ListOrderDetails;
import final_panels.ListOrders;
import final_panels.ListRecievedMessages;
import final_panels.ListRecievedOrders;
import final_panels.ListShortageMedicines;
import final_panels.List_doctor_orders;
import final_panels.Listvendor;
import final_panels.Listvendor_lowestprice;
import final_panels.SearchMedicine;
import final_panels.SearchVendor;
import final_panels.addOrder;
import final_panels.add_doctor_order;
import hmss_project.admin;
import hmss_project.doctoroder;
import java.awt.GridBagConstraints;
import java.awt.GridBagLayout;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JPanel;
import javax.swing.JScrollPane;

/**
 *
 * @author hassan
 */
public class adminDashboard extends javax.swing.JFrame {


    /**
     * Creates new form adminDashboard
     */
    
    AddMedicine p1;
    SearchMedicine p2;
    ListMedicines p3;
    AddVendor p4;
    SearchVendor p5;
    Listvendor p6;
    addOrder p7;
    ListOrders p8;
    ListRecievedMessages p9;
    add_doctor_order p10;
    List_doctor_orders p11;
    Listvendor_lowestprice p12;
    ListShortageMedicines p13;
    
    
    GridBagLayout Layout=new GridBagLayout();

    admin a = new admin();
    
    public adminDashboard() throws SQLException {
        
        initComponents();
        
        RecievedOrdersNotifiaction.setText("("+a.getRecievedOrdersNum()+")");
        shortageNotification.setText("("+a.getShortageListNum()+")");
        
        p1= new AddMedicine();
        p2= new SearchMedicine();
        p3= new ListMedicines();
        p4 = new AddVendor();
        p5 = new SearchVendor();
        p6 = new Listvendor();
        p7 = new addOrder();
        p8 = new ListOrders();
        p9 = new ListRecievedMessages();
        p10= new add_doctor_order();
        p11=new List_doctor_orders();
        p12=new Listvendor_lowestprice();
        p13= new ListShortageMedicines();
                
        AdminPanal.setLayout(Layout);
        
        GridBagConstraints c=new GridBagConstraints();
        c.gridx=0;
        c.gridy=0;
        
        AdminPanal.add(p1,c);
        AdminPanal.add(p2,c);
        AdminPanal.add(p3,c);
        AdminPanal.add(p4,c);
        AdminPanal.add(p5,c);
        AdminPanal.add(p6,c);
        AdminPanal.add(p7,c);
        AdminPanal.add(p8,c);
        AdminPanal.add(p9,c);
        AdminPanal.add(p10,c);
        AdminPanal.add(p11,c);
        AdminPanal.add(p12,c);
        AdminPanal.add(p13,c);
        
        
        p1.setVisible(true);
        p2.setVisible(false);
        p3.setVisible(false);
        p4.setVisible(false);
        p5.setVisible(false);
        p6.setVisible(false);
        p7.setVisible(false);
        p8.setVisible(false);
        p9.setVisible(false);
        p10.setVisible(false);
        p11.setVisible(false);
        p12.setVisible(false);
        p13.setVisible(false);
        
        setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jPanel8 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        AddMedicinePanel = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        searchMedicinePanel = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        ListMedicinePanel = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        addVendorPanal = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        searchVendorPanal = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        ListVendorPanal = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        addOrderPanal = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        ListOrders = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        ListRecievedMessages = new javax.swing.JPanel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        RecievedOrdersNotifiaction = new javax.swing.JLabel();
        addDoctor = new javax.swing.JPanel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        listDoctorOrder = new javax.swing.JPanel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        report = new javax.swing.JPanel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        shortageMedicinesList = new javax.swing.JPanel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        shortageNotification = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel31 = new javax.swing.JLabel();
        AdminPanal = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setAutoscrolls(true);

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 22)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(62, 64, 71));
        jLabel1.setText("Welcome Admin");

        jSeparator1.setBackground(new java.awt.Color(62, 64, 71));
        jSeparator1.setForeground(new java.awt.Color(62, 64, 71));

        AddMedicinePanel.setBackground(new java.awt.Color(242, 242, 242));
        AddMedicinePanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AddMedicinePanelMouseClicked(evt);
            }
        });

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/icons8_Add_32px.png"))); // NOI18N

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(62, 64, 71));
        jLabel5.setText("Add New Medicine ");

        javax.swing.GroupLayout AddMedicinePanelLayout = new javax.swing.GroupLayout(AddMedicinePanel);
        AddMedicinePanel.setLayout(AddMedicinePanelLayout);
        AddMedicinePanelLayout.setHorizontalGroup(
            AddMedicinePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AddMedicinePanelLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel4)
                .addGap(27, 27, 27)
                .addComponent(jLabel5)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        AddMedicinePanelLayout.setVerticalGroup(
            AddMedicinePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, AddMedicinePanelLayout.createSequentialGroup()
                .addContainerGap(21, Short.MAX_VALUE)
                .addComponent(jLabel5)
                .addGap(19, 19, 19))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, AddMedicinePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        searchMedicinePanel.setBackground(new java.awt.Color(255, 255, 255));
        searchMedicinePanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                searchMedicinePanelMouseClicked(evt);
            }
        });

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/icons8_Search_32px_2.png"))); // NOI18N

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(62, 64, 71));
        jLabel7.setText("Search For Medicine");

        javax.swing.GroupLayout searchMedicinePanelLayout = new javax.swing.GroupLayout(searchMedicinePanel);
        searchMedicinePanel.setLayout(searchMedicinePanelLayout);
        searchMedicinePanelLayout.setHorizontalGroup(
            searchMedicinePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(searchMedicinePanelLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel6)
                .addGap(27, 27, 27)
                .addComponent(jLabel7)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        searchMedicinePanelLayout.setVerticalGroup(
            searchMedicinePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(searchMedicinePanelLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel7)
                .addContainerGap(22, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, searchMedicinePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        ListMedicinePanel.setBackground(new java.awt.Color(255, 255, 255));
        ListMedicinePanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ListMedicinePanelMouseClicked(evt);
            }
        });

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/icons8_List_32px.png"))); // NOI18N

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(62, 64, 71));
        jLabel9.setText("List All Medicines");

        javax.swing.GroupLayout ListMedicinePanelLayout = new javax.swing.GroupLayout(ListMedicinePanel);
        ListMedicinePanel.setLayout(ListMedicinePanelLayout);
        ListMedicinePanelLayout.setHorizontalGroup(
            ListMedicinePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ListMedicinePanelLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel8)
                .addGap(27, 27, 27)
                .addComponent(jLabel9)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        ListMedicinePanelLayout.setVerticalGroup(
            ListMedicinePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ListMedicinePanelLayout.createSequentialGroup()
                .addContainerGap(23, Short.MAX_VALUE)
                .addComponent(jLabel9)
                .addGap(19, 19, 19))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ListMedicinePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        addVendorPanal.setBackground(new java.awt.Color(255, 255, 255));
        addVendorPanal.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addVendorPanalMouseClicked(evt);
            }
        });

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/icons8_Add_User_Male_32px_4.png"))); // NOI18N

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(62, 64, 71));
        jLabel11.setText("Add New Vendor ");

        javax.swing.GroupLayout addVendorPanalLayout = new javax.swing.GroupLayout(addVendorPanal);
        addVendorPanal.setLayout(addVendorPanalLayout);
        addVendorPanalLayout.setHorizontalGroup(
            addVendorPanalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addVendorPanalLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel10)
                .addGap(27, 27, 27)
                .addComponent(jLabel11)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        addVendorPanalLayout.setVerticalGroup(
            addVendorPanalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, addVendorPanalLayout.createSequentialGroup()
                .addContainerGap(23, Short.MAX_VALUE)
                .addComponent(jLabel11)
                .addGap(19, 19, 19))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, addVendorPanalLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        searchVendorPanal.setBackground(new java.awt.Color(255, 255, 255));
        searchVendorPanal.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                searchVendorPanalMouseClicked(evt);
            }
        });

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/icons8_Search_32px_2.png"))); // NOI18N

        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(62, 64, 71));
        jLabel13.setText("Search For Vendor");

        javax.swing.GroupLayout searchVendorPanalLayout = new javax.swing.GroupLayout(searchVendorPanal);
        searchVendorPanal.setLayout(searchVendorPanalLayout);
        searchVendorPanalLayout.setHorizontalGroup(
            searchVendorPanalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(searchVendorPanalLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel12)
                .addGap(27, 27, 27)
                .addComponent(jLabel13)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        searchVendorPanalLayout.setVerticalGroup(
            searchVendorPanalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, searchVendorPanalLayout.createSequentialGroup()
                .addContainerGap(23, Short.MAX_VALUE)
                .addComponent(jLabel13)
                .addGap(19, 19, 19))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, searchVendorPanalLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        ListVendorPanal.setBackground(new java.awt.Color(255, 255, 255));
        ListVendorPanal.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ListVendorPanalMouseClicked(evt);
            }
        });

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/icons8_List_32px.png"))); // NOI18N

        jLabel15.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(62, 64, 71));
        jLabel15.setText("List All Vendors");

        javax.swing.GroupLayout ListVendorPanalLayout = new javax.swing.GroupLayout(ListVendorPanal);
        ListVendorPanal.setLayout(ListVendorPanalLayout);
        ListVendorPanalLayout.setHorizontalGroup(
            ListVendorPanalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ListVendorPanalLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel14)
                .addGap(27, 27, 27)
                .addComponent(jLabel15)
                .addContainerGap(93, Short.MAX_VALUE))
        );
        ListVendorPanalLayout.setVerticalGroup(
            ListVendorPanalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ListVendorPanalLayout.createSequentialGroup()
                .addContainerGap(23, Short.MAX_VALUE)
                .addComponent(jLabel15)
                .addGap(19, 19, 19))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ListVendorPanalLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        addOrderPanal.setBackground(new java.awt.Color(255, 255, 255));
        addOrderPanal.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addOrderPanalMouseClicked(evt);
            }
        });

        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/icons8_Add_Shopping_Cart_32px_1.png"))); // NOI18N

        jLabel17.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(62, 64, 71));
        jLabel17.setText("Add New order");

        javax.swing.GroupLayout addOrderPanalLayout = new javax.swing.GroupLayout(addOrderPanal);
        addOrderPanal.setLayout(addOrderPanalLayout);
        addOrderPanalLayout.setHorizontalGroup(
            addOrderPanalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addOrderPanalLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel16)
                .addGap(27, 27, 27)
                .addComponent(jLabel17)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        addOrderPanalLayout.setVerticalGroup(
            addOrderPanalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, addOrderPanalLayout.createSequentialGroup()
                .addContainerGap(23, Short.MAX_VALUE)
                .addComponent(jLabel17)
                .addGap(19, 19, 19))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, addOrderPanalLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel16, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        ListOrders.setBackground(new java.awt.Color(255, 255, 255));
        ListOrders.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ListOrdersMouseClicked(evt);
            }
        });

        jLabel18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/icons8_List_32px.png"))); // NOI18N

        jLabel19.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(62, 64, 71));
        jLabel19.setText("List orders");

        javax.swing.GroupLayout ListOrdersLayout = new javax.swing.GroupLayout(ListOrders);
        ListOrders.setLayout(ListOrdersLayout);
        ListOrdersLayout.setHorizontalGroup(
            ListOrdersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ListOrdersLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel18)
                .addGap(27, 27, 27)
                .addComponent(jLabel19)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        ListOrdersLayout.setVerticalGroup(
            ListOrdersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ListOrdersLayout.createSequentialGroup()
                .addContainerGap(23, Short.MAX_VALUE)
                .addComponent(jLabel19)
                .addGap(19, 19, 19))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ListOrdersLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel18, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        ListRecievedMessages.setBackground(new java.awt.Color(255, 255, 255));
        ListRecievedMessages.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ListRecievedMessagesMouseClicked(evt);
            }
        });

        jLabel20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/icons8_Gmail_Login_32px.png"))); // NOI18N

        jLabel21.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(62, 64, 71));
        jLabel21.setText("List Recieved messages");

        RecievedOrdersNotifiaction.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        RecievedOrdersNotifiaction.setForeground(new java.awt.Color(255, 51, 51));
        RecievedOrdersNotifiaction.setText("(0)");

        javax.swing.GroupLayout ListRecievedMessagesLayout = new javax.swing.GroupLayout(ListRecievedMessages);
        ListRecievedMessages.setLayout(ListRecievedMessagesLayout);
        ListRecievedMessagesLayout.setHorizontalGroup(
            ListRecievedMessagesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ListRecievedMessagesLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel20)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(RecievedOrdersNotifiaction)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel21)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        ListRecievedMessagesLayout.setVerticalGroup(
            ListRecievedMessagesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ListRecievedMessagesLayout.createSequentialGroup()
                .addContainerGap(23, Short.MAX_VALUE)
                .addGroup(ListRecievedMessagesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel21)
                    .addComponent(RecievedOrdersNotifiaction))
                .addGap(19, 19, 19))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ListRecievedMessagesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel20, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        addDoctor.setBackground(new java.awt.Color(255, 255, 255));
        addDoctor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addDoctorMouseClicked(evt);
            }
        });

        jLabel22.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/icons8_Add_32px.png"))); // NOI18N

        jLabel23.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(62, 64, 71));
        jLabel23.setText("Add Doctor order");

        javax.swing.GroupLayout addDoctorLayout = new javax.swing.GroupLayout(addDoctor);
        addDoctor.setLayout(addDoctorLayout);
        addDoctorLayout.setHorizontalGroup(
            addDoctorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addDoctorLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel22)
                .addGap(33, 33, 33)
                .addComponent(jLabel23)
                .addContainerGap(70, Short.MAX_VALUE))
        );
        addDoctorLayout.setVerticalGroup(
            addDoctorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, addDoctorLayout.createSequentialGroup()
                .addContainerGap(23, Short.MAX_VALUE)
                .addComponent(jLabel23)
                .addGap(19, 19, 19))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, addDoctorLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel22, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        listDoctorOrder.setBackground(new java.awt.Color(255, 255, 255));
        listDoctorOrder.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                listDoctorOrderMouseClicked(evt);
            }
        });

        jLabel24.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/icons8_List_32px.png"))); // NOI18N

        jLabel25.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(62, 64, 71));
        jLabel25.setText("List Doctor order");

        javax.swing.GroupLayout listDoctorOrderLayout = new javax.swing.GroupLayout(listDoctorOrder);
        listDoctorOrder.setLayout(listDoctorOrderLayout);
        listDoctorOrderLayout.setHorizontalGroup(
            listDoctorOrderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(listDoctorOrderLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel24)
                .addGap(33, 33, 33)
                .addComponent(jLabel25)
                .addContainerGap(76, Short.MAX_VALUE))
        );
        listDoctorOrderLayout.setVerticalGroup(
            listDoctorOrderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel24, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 62, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, listDoctorOrderLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel25)
                .addGap(19, 19, 19))
        );

        report.setBackground(new java.awt.Color(255, 255, 255));
        report.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                reportMouseClicked(evt);
            }
        });

        jLabel26.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/icons8_Increase_32px.png"))); // NOI18N

        jLabel27.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(62, 64, 71));
        jLabel27.setText("Report");

        javax.swing.GroupLayout reportLayout = new javax.swing.GroupLayout(report);
        report.setLayout(reportLayout);
        reportLayout.setHorizontalGroup(
            reportLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(reportLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel26)
                .addGap(33, 33, 33)
                .addComponent(jLabel27)
                .addContainerGap(144, Short.MAX_VALUE))
        );
        reportLayout.setVerticalGroup(
            reportLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, reportLayout.createSequentialGroup()
                .addContainerGap(23, Short.MAX_VALUE)
                .addComponent(jLabel27)
                .addGap(19, 19, 19))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, reportLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel26, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        shortageMedicinesList.setBackground(new java.awt.Color(255, 255, 255));
        shortageMedicinesList.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                shortageMedicinesListMouseClicked(evt);
            }
        });

        jLabel28.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/icons8_List_32px.png"))); // NOI18N

        jLabel29.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel29.setForeground(new java.awt.Color(62, 64, 71));
        jLabel29.setText("List Shortage Medicines");

        shortageNotification.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        shortageNotification.setForeground(new java.awt.Color(255, 51, 51));
        shortageNotification.setText("(0)");

        javax.swing.GroupLayout shortageMedicinesListLayout = new javax.swing.GroupLayout(shortageMedicinesList);
        shortageMedicinesList.setLayout(shortageMedicinesListLayout);
        shortageMedicinesListLayout.setHorizontalGroup(
            shortageMedicinesListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(shortageMedicinesListLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel28)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(shortageNotification)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel29)
                .addContainerGap(32, Short.MAX_VALUE))
        );
        shortageMedicinesListLayout.setVerticalGroup(
            shortageMedicinesListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, shortageMedicinesListLayout.createSequentialGroup()
                .addContainerGap(23, Short.MAX_VALUE)
                .addGroup(shortageMedicinesListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel29)
                    .addComponent(shortageNotification))
                .addGap(19, 19, 19))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, shortageMedicinesListLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel28, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel5.setBackground(new java.awt.Color(153, 0, 0));
        jPanel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel5MouseClicked(evt);
            }
        });

        jLabel31.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel31.setForeground(new java.awt.Color(255, 255, 255));
        jLabel31.setText("Logout");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(jLabel31)
                .addContainerGap(44, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel31)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(AddMedicinePanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(searchMedicinePanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(ListMedicinePanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(addVendorPanal, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(searchVendorPanal, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(ListVendorPanal, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(addOrderPanal, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(ListOrders, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(ListRecievedMessages, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(addDoctor, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(listDoctorOrder, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(report, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(shortageMedicinesList, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(68, 68, 68)
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(3, 3, 3)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(AddMedicinePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(searchMedicinePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(ListMedicinePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(addVendorPanal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(searchVendorPanal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(ListVendorPanal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(addOrderPanal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(ListOrders, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(ListRecievedMessages, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(addDoctor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(listDoctorOrder, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(report, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(shortageMedicinesList, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(251, Short.MAX_VALUE))
        );

        AdminPanal.setBackground(new java.awt.Color(252, 252, 252));

        javax.swing.GroupLayout AdminPanalLayout = new javax.swing.GroupLayout(AdminPanal);
        AdminPanal.setLayout(AdminPanalLayout);
        AdminPanalLayout.setHorizontalGroup(
            AdminPanalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 805, Short.MAX_VALUE)
        );
        AdminPanalLayout.setVerticalGroup(
            AdminPanalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(AdminPanal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(AdminPanal, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jScrollPane2.setViewportView(jPanel8);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 608, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AddMedicinePanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AddMedicinePanelMouseClicked
        AddMedicinePanel.setBackground(new java.awt.Color(242,242,242));
        ListMedicinePanel.setBackground(new java.awt.Color(255,255,255));
        searchMedicinePanel.setBackground(new java.awt.Color(255,255,255));
        addVendorPanal.setBackground(new java.awt.Color(255,255,255));
        searchVendorPanal.setBackground(new java.awt.Color(255,255,255));
        ListVendorPanal.setBackground(new java.awt.Color(255,255,255));
        addOrderPanal.setBackground(new java.awt.Color(255,255,255));
        ListOrders.setBackground(new java.awt.Color(255,255,255));
        ListRecievedMessages.setBackground(new java.awt.Color(255,255,255));
        addDoctor.setBackground(new java.awt.Color(255,255,255));
        listDoctorOrder.setBackground(new java.awt.Color(255,255,255));
        report.setBackground(new java.awt.Color(255,255,255));
        shortageMedicinesList.setBackground(new java.awt.Color(255,255,255));
        
        p1.setVisible(true);
        p2.setVisible(false);
        p4.setVisible(false);
        p5.setVisible(false);   
        p6.setVisible(false);
        p7.setVisible(false);
        p8.setVisible(false);
        p9.setVisible(false);
        p10.setVisible(false);
        p11.setVisible(false);
        p12.setVisible(false);
        p13.setVisible(false);
        p3.setVisible(false);    }//GEN-LAST:event_AddMedicinePanelMouseClicked

    private void searchMedicinePanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_searchMedicinePanelMouseClicked
        // TODO add your handling code here:
        
        
        AddMedicinePanel.setBackground(new java.awt.Color(255,255,255));
        ListMedicinePanel.setBackground(new java.awt.Color(255,255,255));
        searchMedicinePanel.setBackground(new java.awt.Color(242,242,242));
        addVendorPanal.setBackground(new java.awt.Color(255,255,255));
        searchVendorPanal.setBackground(new java.awt.Color(255,255,255));
        ListVendorPanal.setBackground(new java.awt.Color(255,255,255));
        addOrderPanal.setBackground(new java.awt.Color(255,255,255));
        ListOrders.setBackground(new java.awt.Color(255,255,255));
        ListRecievedMessages.setBackground(new java.awt.Color(255,255,255));
        addDoctor.setBackground(new java.awt.Color(255,255,255));
        listDoctorOrder.setBackground(new java.awt.Color(255,255,255));
        report.setBackground(new java.awt.Color(255,255,255));
        shortageMedicinesList.setBackground(new java.awt.Color(255,255,255));
        
        p1.setVisible(false);
        p2.setVisible(true);
        p3.setVisible(false);
        p4.setVisible(false);
        p5.setVisible(false);
        p6.setVisible(false);
        p7.setVisible(false);
        p8.setVisible(false);
        p9.setVisible(false);
        p10.setVisible(false);
        p11.setVisible(false);
        p12.setVisible(false);
        p13.setVisible(false);
    }//GEN-LAST:event_searchMedicinePanelMouseClicked

    private void ListMedicinePanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ListMedicinePanelMouseClicked
        
        p3.deleteTable(); 
        p3.addRowsTojTable();
       AddMedicinePanel.setBackground(new java.awt.Color(255,255,255));
        ListMedicinePanel.setBackground(new java.awt.Color(242,242,242));
        searchMedicinePanel.setBackground(new java.awt.Color(255,255,255));
        addVendorPanal.setBackground(new java.awt.Color(255,255,255));
        searchVendorPanal.setBackground(new java.awt.Color(255,255,255));
        ListVendorPanal.setBackground(new java.awt.Color(255,255,255));
        addOrderPanal.setBackground(new java.awt.Color(255,255,255));
        ListOrders.setBackground(new java.awt.Color(255,255,255));
        ListRecievedMessages.setBackground(new java.awt.Color(255,255,255));
        addDoctor.setBackground(new java.awt.Color(255,255,255));
        listDoctorOrder.setBackground(new java.awt.Color(255,255,255));
        report.setBackground(new java.awt.Color(255,255,255));
        shortageMedicinesList.setBackground(new java.awt.Color(255,255,255));
        
        p1.setVisible(false);
        p2.setVisible(false);
        p3.setVisible(true);
        p4.setVisible(false);
        p5.setVisible(false);
        p6.setVisible(false);
        p7.setVisible(false);
        p8.setVisible(false);
        p9.setVisible(false);
        p10.setVisible(false);
        p11.setVisible(false);
        p12.setVisible(false);
        p13.setVisible(false);
        
    }//GEN-LAST:event_ListMedicinePanelMouseClicked

    private void addVendorPanalMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addVendorPanalMouseClicked
        
         AddMedicinePanel.setBackground(new java.awt.Color(255,255,255));
        ListMedicinePanel.setBackground(new java.awt.Color(255,255,255));
        searchMedicinePanel.setBackground(new java.awt.Color(255,255,255));
        addVendorPanal.setBackground(new java.awt.Color(242,242,242));
        searchVendorPanal.setBackground(new java.awt.Color(255,255,255));
        ListVendorPanal.setBackground(new java.awt.Color(255,255,255));
        addOrderPanal.setBackground(new java.awt.Color(255,255,255));
        ListOrders.setBackground(new java.awt.Color(255,255,255));
        ListRecievedMessages.setBackground(new java.awt.Color(255,255,255));
        addDoctor.setBackground(new java.awt.Color(255,255,255));
        listDoctorOrder.setBackground(new java.awt.Color(255,255,255));
        report.setBackground(new java.awt.Color(255,255,255));
        shortageMedicinesList.setBackground(new java.awt.Color(255,255,255));
        
        p1.setVisible(false);
        p2.setVisible(false);
        p3.setVisible(false);
        p4.setVisible(true);
        p5.setVisible(false);
        p6.setVisible(false);
        p7.setVisible(false);
        p8.setVisible(false);
        p9.setVisible(false);
        p10.setVisible(false);
        p11.setVisible(false);
        p12.setVisible(false);
        p13.setVisible(false);
    }//GEN-LAST:event_addVendorPanalMouseClicked

    private void searchVendorPanalMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_searchVendorPanalMouseClicked
        AddMedicinePanel.setBackground(new java.awt.Color(255,255,255));
        ListMedicinePanel.setBackground(new java.awt.Color(255,255,255));
        searchMedicinePanel.setBackground(new java.awt.Color(255,255,255));
        addVendorPanal.setBackground(new java.awt.Color(255,255,255));
        searchVendorPanal.setBackground(new java.awt.Color(242,242,242));
        ListVendorPanal.setBackground(new java.awt.Color(255,255,255));
        addOrderPanal.setBackground(new java.awt.Color(255,255,255));
        ListOrders.setBackground(new java.awt.Color(255,255,255));
        ListRecievedMessages.setBackground(new java.awt.Color(255,255,255));
        addDoctor.setBackground(new java.awt.Color(255,255,255));
        listDoctorOrder.setBackground(new java.awt.Color(255,255,255));
        report.setBackground(new java.awt.Color(255,255,255));
        shortageMedicinesList.setBackground(new java.awt.Color(255,255,255));
        
        p1.setVisible(false);
        p2.setVisible(false);
        p3.setVisible(false);
        p4.setVisible(false);
        p5.setVisible(true);
        p6.setVisible(false);
        p7.setVisible(false);
        p8.setVisible(false);
        p9.setVisible(false);
        p10.setVisible(false);
        p11.setVisible(false);
        p12.setVisible(false);
        p13.setVisible(false);
    }//GEN-LAST:event_searchVendorPanalMouseClicked

    private void ListVendorPanalMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ListVendorPanalMouseClicked
        p6.deleteTable(); 
        p6.addRowsTojTable();
        
         AddMedicinePanel.setBackground(new java.awt.Color(255,255,255));
        ListMedicinePanel.setBackground(new java.awt.Color(255,255,255));
        searchMedicinePanel.setBackground(new java.awt.Color(255,255,255));
        addVendorPanal.setBackground(new java.awt.Color(255,255,255));
        searchVendorPanal.setBackground(new java.awt.Color(255,255,255));
        ListVendorPanal.setBackground(new java.awt.Color(242,242,242));
        addOrderPanal.setBackground(new java.awt.Color(255,255,255));
        ListOrders.setBackground(new java.awt.Color(255,255,255));
        ListRecievedMessages.setBackground(new java.awt.Color(255,255,255));
        addDoctor.setBackground(new java.awt.Color(255,255,255));
        listDoctorOrder.setBackground(new java.awt.Color(255,255,255));
        report.setBackground(new java.awt.Color(255,255,255));
        shortageMedicinesList.setBackground(new java.awt.Color(255,255,255));
        
        p1.setVisible(false);
        p2.setVisible(false);
        p3.setVisible(false);
        p4.setVisible(false);
        p5.setVisible(false);
        p6.setVisible(true);
        p7.setVisible(false);
        p8.setVisible(false);
        p9.setVisible(false);
        p10.setVisible(false);
        p11.setVisible(false);
        p12.setVisible(false);
        p13.setVisible(false);

    }//GEN-LAST:event_ListVendorPanalMouseClicked

    private void addOrderPanalMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addOrderPanalMouseClicked
        // TODO add your handling code here:
        
 AddMedicinePanel.setBackground(new java.awt.Color(255,255,255));
        ListMedicinePanel.setBackground(new java.awt.Color(255,255,255));
        searchMedicinePanel.setBackground(new java.awt.Color(255,255,255));
        addVendorPanal.setBackground(new java.awt.Color(255,255,255));
        searchVendorPanal.setBackground(new java.awt.Color(255,255,255));
        ListVendorPanal.setBackground(new java.awt.Color(255,255,255));
        addOrderPanal.setBackground(new java.awt.Color(242,242,242));
        ListOrders.setBackground(new java.awt.Color(255,255,255));
        ListRecievedMessages.setBackground(new java.awt.Color(255,255,255));
        addDoctor.setBackground(new java.awt.Color(255,255,255));
        listDoctorOrder.setBackground(new java.awt.Color(255,255,255));
        report.setBackground(new java.awt.Color(255,255,255));
        shortageMedicinesList.setBackground(new java.awt.Color(255,255,255));
        
        p1.setVisible(false);
        p2.setVisible(false);
        p3.setVisible(false);
        p4.setVisible(false);
        p5.setVisible(false);
        p6.setVisible(false);
        p7.setVisible(true);
        p8.setVisible(false);
        p9.setVisible(false);
        p10.setVisible(false);
        p11.setVisible(false);
        p12.setVisible(false);
        p13.setVisible(false);
        
    }//GEN-LAST:event_addOrderPanalMouseClicked

    private void ListOrdersMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ListOrdersMouseClicked
        // TODO add your handling code here:
        
        p8.deleteTable(); 
        try {
            p8.addRowsToTable();
        } catch (SQLException ex) {
            Logger.getLogger(adminDashboard.class.getName()).log(Level.SEVERE, null, ex);
        }
        AddMedicinePanel.setBackground(new java.awt.Color(255,255,255));
        ListMedicinePanel.setBackground(new java.awt.Color(255,255,255));
        searchMedicinePanel.setBackground(new java.awt.Color(255,255,255));
        addVendorPanal.setBackground(new java.awt.Color(255,255,255));
        searchVendorPanal.setBackground(new java.awt.Color(255,255,255));
        ListVendorPanal.setBackground(new java.awt.Color(255,255,255));
        addOrderPanal.setBackground(new java.awt.Color(255,255,255));
        ListOrders.setBackground(new java.awt.Color(242,242,242));
        ListRecievedMessages.setBackground(new java.awt.Color(255,255,255));
        addDoctor.setBackground(new java.awt.Color(255,255,255));
        listDoctorOrder.setBackground(new java.awt.Color(255,255,255));
        report.setBackground(new java.awt.Color(255,255,255));
        shortageMedicinesList.setBackground(new java.awt.Color(255,255,255));
        
        p1.setVisible(false);
        p2.setVisible(false);
        p3.setVisible(false);
        p4.setVisible(false);
        p5.setVisible(false);
        p6.setVisible(false);
        p7.setVisible(false);
        p8.setVisible(true);
        p9.setVisible(false);
        p10.setVisible(false);
        p11.setVisible(false);
        p12.setVisible(false);
        p13.setVisible(false);
    }//GEN-LAST:event_ListOrdersMouseClicked

    private void ListRecievedMessagesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ListRecievedMessagesMouseClicked
        // TODO add your handling code here:
        
       AddMedicinePanel.setBackground(new java.awt.Color(255,255,255));
        ListMedicinePanel.setBackground(new java.awt.Color(255,255,255));
        searchMedicinePanel.setBackground(new java.awt.Color(255,255,255));
        addVendorPanal.setBackground(new java.awt.Color(255,255,255));
        searchVendorPanal.setBackground(new java.awt.Color(255,255,255));
        ListVendorPanal.setBackground(new java.awt.Color(255,255,255));
        addOrderPanal.setBackground(new java.awt.Color(255,255,255));
        ListOrders.setBackground(new java.awt.Color(255,255,255));
        ListRecievedMessages.setBackground(new java.awt.Color(242,242,242));
        addDoctor.setBackground(new java.awt.Color(255,255,255));
        listDoctorOrder.setBackground(new java.awt.Color(255,255,255));
        report.setBackground(new java.awt.Color(255,255,255));
        shortageMedicinesList.setBackground(new java.awt.Color(255,255,255));
        
        p1.setVisible(false);
        p2.setVisible(false);
        p3.setVisible(false);
        p4.setVisible(false);
        p5.setVisible(false);
        p6.setVisible(false);
        p7.setVisible(false);
        p8.setVisible(false);
        p9.setVisible(true);
        p10.setVisible(false);
        p11.setVisible(false);
        p12.setVisible(false);
        p13.setVisible(false);
    }//GEN-LAST:event_ListRecievedMessagesMouseClicked

    private void addDoctorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addDoctorMouseClicked
        // TODO add your handling code here:
       AddMedicinePanel.setBackground(new java.awt.Color(255,255,255));
        ListMedicinePanel.setBackground(new java.awt.Color(255,255,255));
        searchMedicinePanel.setBackground(new java.awt.Color(255,255,255));
        addVendorPanal.setBackground(new java.awt.Color(255,255,255));
        searchVendorPanal.setBackground(new java.awt.Color(255,255,255));
        ListVendorPanal.setBackground(new java.awt.Color(255,255,255));
        addOrderPanal.setBackground(new java.awt.Color(255,255,255));
        ListOrders.setBackground(new java.awt.Color(255,255,255));
        ListRecievedMessages.setBackground(new java.awt.Color(255,255,255));
        addDoctor.setBackground(new java.awt.Color(242,242,242));
        listDoctorOrder.setBackground(new java.awt.Color(255,255,255));
        report.setBackground(new java.awt.Color(255,255,255));
        shortageMedicinesList.setBackground(new java.awt.Color(255,255,255));
        
        p1.setVisible(false);
        p2.setVisible(false);
        p3.setVisible(false);
        p4.setVisible(false);
        p5.setVisible(false);
        p6.setVisible(false);
        p7.setVisible(false);
        p8.setVisible(false);
        p9.setVisible(false);
        p10.setVisible(true);
        p11.setVisible(false);
        p12.setVisible(false);
        p13.setVisible(false);
    }//GEN-LAST:event_addDoctorMouseClicked

    private void listDoctorOrderMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_listDoctorOrderMouseClicked
        // TODO add your handling code here:
        
        AddMedicinePanel.setBackground(new java.awt.Color(255,255,255));
        ListMedicinePanel.setBackground(new java.awt.Color(255,255,255));
        searchMedicinePanel.setBackground(new java.awt.Color(255,255,255));
        addVendorPanal.setBackground(new java.awt.Color(255,255,255));
        searchVendorPanal.setBackground(new java.awt.Color(255,255,255));
        ListVendorPanal.setBackground(new java.awt.Color(255,255,255));
        addOrderPanal.setBackground(new java.awt.Color(255,255,255));
        ListOrders.setBackground(new java.awt.Color(255,255,255));
        ListRecievedMessages.setBackground(new java.awt.Color(255,255,255));
        addDoctor.setBackground(new java.awt.Color(255,255,255));
        listDoctorOrder.setBackground(new java.awt.Color(242,242,242));
        report.setBackground(new java.awt.Color(255,255,255));
        shortageMedicinesList.setBackground(new java.awt.Color(255,255,255));

        
        p1.setVisible(false);
        p2.setVisible(false);
        p3.setVisible(false);
        p4.setVisible(false);
        p5.setVisible(false);
        p6.setVisible(false);
        p7.setVisible(false);
        p8.setVisible(false);
        p9.setVisible(false);
        p10.setVisible(false);
        p11.setVisible(true);
        p12.setVisible(false);
        p13.setVisible(false);
    }//GEN-LAST:event_listDoctorOrderMouseClicked

    private void reportMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_reportMouseClicked
       AddMedicinePanel.setBackground(new java.awt.Color(255,255,255));
        ListMedicinePanel.setBackground(new java.awt.Color(255,255,255));
        searchMedicinePanel.setBackground(new java.awt.Color(255,255,255));
        addVendorPanal.setBackground(new java.awt.Color(255,255,255));
        searchVendorPanal.setBackground(new java.awt.Color(255,255,255));
        ListVendorPanal.setBackground(new java.awt.Color(255,255,255));
        addOrderPanal.setBackground(new java.awt.Color(255,255,255));
        ListOrders.setBackground(new java.awt.Color(255,255,255));
        ListRecievedMessages.setBackground(new java.awt.Color(255,255,255));
        addDoctor.setBackground(new java.awt.Color(255,255,255));
        listDoctorOrder.setBackground(new java.awt.Color(255,255,255));
        report.setBackground(new java.awt.Color(242,242,242));
        shortageMedicinesList.setBackground(new java.awt.Color(255,255,255));

        
        p1.setVisible(false);
        p2.setVisible(false);
        p3.setVisible(false);
        p4.setVisible(false);
        p5.setVisible(false);
        p6.setVisible(false);
        p7.setVisible(false);
        p8.setVisible(false);
        p9.setVisible(false);
        p10.setVisible(false);
        p11.setVisible(false);
        p12.setVisible(true);
        p13.setVisible(false);




        // TODO add your handling code here:
    }//GEN-LAST:event_reportMouseClicked

    private void shortageMedicinesListMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_shortageMedicinesListMouseClicked
        // TODO add your handling code here:
        
       AddMedicinePanel.setBackground(new java.awt.Color(255,255,255));
        ListMedicinePanel.setBackground(new java.awt.Color(255,255,255));
        searchMedicinePanel.setBackground(new java.awt.Color(255,255,255));
        addVendorPanal.setBackground(new java.awt.Color(255,255,255));
        searchVendorPanal.setBackground(new java.awt.Color(255,255,255));
        ListVendorPanal.setBackground(new java.awt.Color(255,255,255));
        addOrderPanal.setBackground(new java.awt.Color(255,255,255));
        ListOrders.setBackground(new java.awt.Color(255,255,255));
        ListRecievedMessages.setBackground(new java.awt.Color(255,255,255));
        addDoctor.setBackground(new java.awt.Color(255,255,255));
        listDoctorOrder.setBackground(new java.awt.Color(255,255,255));
        shortageMedicinesList.setBackground(new java.awt.Color(242,242,242));
        report.setBackground(new java.awt.Color(255,255,255));

        
        p1.setVisible(false);
        p2.setVisible(false);
        p3.setVisible(false);
        p4.setVisible(false);
        p5.setVisible(false);
        p6.setVisible(false);
        p7.setVisible(false);
        p8.setVisible(false);
        p9.setVisible(false);
        p10.setVisible(false);
        p11.setVisible(false);
        p12.setVisible(false);
        p13.setVisible(true);

        
    }//GEN-LAST:event_shortageMedicinesListMouseClicked

    private void jPanel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel5MouseClicked
        this.setVisible(false);
        new LoginFrame().setVisible(true);
    }//GEN-LAST:event_jPanel5MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
        JScrollPane scroll = new JScrollPane(null,JScrollPane.VERTICAL_SCROLLBAR_AS_NEEDED,JScrollPane.HORIZONTAL_SCROLLBAR_AS_NEEDED);
        
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(adminDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(adminDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(adminDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(adminDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {  
                    new adminDashboard().setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(adminDashboard.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel AddMedicinePanel;
    private javax.swing.JPanel AdminPanal;
    private javax.swing.JPanel ListMedicinePanel;
    private javax.swing.JPanel ListOrders;
    private javax.swing.JPanel ListRecievedMessages;
    private javax.swing.JPanel ListVendorPanal;
    private javax.swing.JLabel RecievedOrdersNotifiaction;
    private javax.swing.JPanel addDoctor;
    private javax.swing.JPanel addOrderPanal;
    private javax.swing.JPanel addVendorPanal;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JPanel listDoctorOrder;
    private javax.swing.JPanel report;
    private javax.swing.JPanel searchMedicinePanel;
    private javax.swing.JPanel searchVendorPanal;
    private javax.swing.JPanel shortageMedicinesList;
    private javax.swing.JLabel shortageNotification;
    // End of variables declaration//GEN-END:variables
}
