/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import java.awt.Color;
import java.awt.Container;
import javafx.scene.layout.Background;
import javax.swing.JFrame;
import hmss_project.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import sun.awt.EmbeddedFrame;

/**
 *
 * @author hassan
 */
public class LoginFrame extends javax.swing.JFrame {

    /**
     * Creates new form LoginFrame
     */
    public LoginFrame() {
        initComponents();
        getContentPane().setBackground(new Color(255,255,255));
        setExtendedState(JFrame.MAXIMIZED_HORIZ);
        setVisible(true);
        setResizable(false);
 

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        login_UsernameField = new javax.swing.JTextField();
        login_UsernameLabel = new javax.swing.JLabel();
        login_passwordLabel = new javax.swing.JLabel();
        login_PasswordField = new javax.swing.JPasswordField();
        jLabel3 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        login_loginButton = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        Login_CloseButton = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setLocation(new java.awt.Point(60, 60));

        login_UsernameField.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        login_UsernameField.setForeground(new java.awt.Color(62, 64, 71));
        login_UsernameField.setBorder(null);
        login_UsernameField.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                login_UsernameFieldMouseClicked(evt);
            }
        });
        login_UsernameField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                login_UsernameFieldActionPerformed(evt);
            }
        });

        login_UsernameLabel.setFont(new java.awt.Font("Gotham Book", 1, 14)); // NOI18N
        login_UsernameLabel.setForeground(new java.awt.Color(62, 64, 71));
        login_UsernameLabel.setText("Username");

        login_passwordLabel.setFont(new java.awt.Font("Gotham Book", 1, 14)); // NOI18N
        login_passwordLabel.setForeground(new java.awt.Color(62, 64, 71));
        login_passwordLabel.setText("password");

        login_PasswordField.setForeground(new java.awt.Color(62, 64, 71));
        login_PasswordField.setBorder(null);
        login_PasswordField.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                login_PasswordFieldMouseClicked(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Gotham Book", 0, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(62, 64, 71));
        jLabel3.setText("LOGIN");

        jPanel1.setBackground(new java.awt.Color(0, 167, 87));

        login_loginButton.setFont(new java.awt.Font("Gotham Book", 0, 12)); // NOI18N
        login_loginButton.setForeground(new java.awt.Color(255, 255, 255));
        login_loginButton.setText("LOGIN");
        login_loginButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                login_loginButtonMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(login_loginButton)
                .addContainerGap(50, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(login_loginButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(223, 74, 50));

        Login_CloseButton.setFont(new java.awt.Font("Gotham Book", 0, 12)); // NOI18N
        Login_CloseButton.setForeground(new java.awt.Color(255, 255, 255));
        Login_CloseButton.setText("CLOSE");
        Login_CloseButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Login_CloseButtonMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addComponent(Login_CloseButton)
                .addContainerGap(54, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Login_CloseButton)
                .addContainerGap())
        );

        jSeparator1.setForeground(new java.awt.Color(255, 255, 255));

        jSeparator2.setForeground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(180, 180, 180)
                        .addComponent(jLabel3))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(76, 76, 76)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(login_UsernameLabel)
                                .addGap(230, 230, 230))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(login_passwordLabel)
                                .addGap(233, 233, 233))
                            .addComponent(jSeparator1)
                            .addComponent(login_UsernameField)
                            .addComponent(login_PasswordField)
                            .addComponent(jSeparator2))))
                .addGap(78, 78, 78))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addComponent(jLabel3)
                .addGap(31, 31, 31)
                .addComponent(login_UsernameLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(login_UsernameField, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41)
                .addComponent(login_passwordLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(login_PasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 2, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(58, 58, 58)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(86, 86, 86))
        );

        setSize(new java.awt.Dimension(457, 487));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void login_UsernameFieldMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_login_UsernameFieldMouseClicked
        login_UsernameField.setText("");
    }//GEN-LAST:event_login_UsernameFieldMouseClicked

    private void login_PasswordFieldMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_login_PasswordFieldMouseClicked
        login_PasswordField.setText("");
    }//GEN-LAST:event_login_PasswordFieldMouseClicked

    private void login_loginButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_login_loginButtonMouseClicked
        vendor x = new vendor();
        admin a = new admin();
        int vid=0;
        try {
            String pass = x.loginVendor(login_UsernameField.getText());
            
            if(pass.equals(login_PasswordField.getText()))
            {
                this.setVisible(false);
                
                vid= x.tkvID(login_UsernameField.getText());
                x.addLog(vid);
                
                new vendorDashboard().setVisible(true);
            }
            else
            {
                pass = a.loginAdmin(login_UsernameField.getText());
            
                if(pass.equals(login_PasswordField.getText()))
                {
                    this.setVisible(false);
                    new adminDashboard().setVisible(true);
                }
                else
                {
                    JOptionPane.showMessageDialog(null," Enter valid username or password !");
                }
                
            }
        } 
        
        catch (SQLException ex) {
            Logger.getLogger(LoginFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
       
    }//GEN-LAST:event_login_loginButtonMouseClicked

    private void Login_CloseButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Login_CloseButtonMouseClicked
        System.exit(0);
    }//GEN-LAST:event_Login_CloseButtonMouseClicked

    private void login_UsernameFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_login_UsernameFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_login_UsernameFieldActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
    
    /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new LoginFrame().setVisible(true);
        });
        
        

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Login_CloseButton;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JPasswordField login_PasswordField;
    private javax.swing.JTextField login_UsernameField;
    private javax.swing.JLabel login_UsernameLabel;
    private javax.swing.JLabel login_loginButton;
    private javax.swing.JLabel login_passwordLabel;
    // End of variables declaration//GEN-END:variables

   
}
