/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package final_panels;

import panels.*;
import com.sun.javafx.iio.ios.IosImageLoader;
import java.io.File;
import java.io.IOException;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JTextField;
import hmss_project.admin;
import hmss_project.doctoroder;
import hmss_project.doctororderdetails;
import hmss_project.medicine;
import hmss_project.order;
import hmss_project.orderDetails;
import java.awt.BorderLayout;
import java.awt.Dimension;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.border.EmptyBorder;

/**
 *
 * @author pc
 */
public class add_doctor_order extends javax.swing.JPanel {

    ListMedicines l = null;
    medicine m,n = null;
    add_doctor_OrderDetails doc_order ;  
    admin a = new admin();
    doctoroder doc_orderr;
    
    ArrayList<doctororderdetails> orderD = new ArrayList<>();

    
    
    /**
     * Creates new form AddEmployee
     */
    
    public add_doctor_order() {
        initComponents();
       
    }
   
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        addOrder = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        add_btn = new javax.swing.JPanel();
        jAddEmployee = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        numberOfOrders = new javax.swing.JTextField();
        jSeparator5 = new javax.swing.JSeparator();
        jLabel5 = new javax.swing.JLabel();
        doctorNameEditText = new javax.swing.JTextField();
        jSeparator6 = new javax.swing.JSeparator();

        addOrder.setBackground(new java.awt.Color(242, 242, 242));
        addOrder.setAutoscrolls(true);

        jLabel14.setBackground(new java.awt.Color(36, 49, 60));
        jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(63, 85, 105));
        jLabel14.setText("Enter doctor order Information");

        add_btn.setBackground(new java.awt.Color(0, 167, 87));
        add_btn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                add_btnMouseClicked(evt);
            }
        });

        jAddEmployee.setBackground(new java.awt.Color(255, 255, 255));
        jAddEmployee.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jAddEmployee.setForeground(new java.awt.Color(255, 255, 255));
        jAddEmployee.setText("ADD");

        javax.swing.GroupLayout add_btnLayout = new javax.swing.GroupLayout(add_btn);
        add_btn.setLayout(add_btnLayout);
        add_btnLayout.setHorizontalGroup(
            add_btnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, add_btnLayout.createSequentialGroup()
                .addContainerGap(50, Short.MAX_VALUE)
                .addComponent(jAddEmployee)
                .addGap(48, 48, 48))
        );
        add_btnLayout.setVerticalGroup(
            add_btnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(add_btnLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jAddEmployee, javax.swing.GroupLayout.DEFAULT_SIZE, 26, Short.MAX_VALUE)
                .addContainerGap())
        );

        jLabel4.setBackground(new java.awt.Color(36, 49, 60));
        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(62, 64, 71));
        jLabel4.setText("number of orders");

        numberOfOrders.setBackground(new java.awt.Color(242, 242, 242));
        numberOfOrders.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        numberOfOrders.setForeground(new java.awt.Color(36, 49, 60));
        numberOfOrders.setBorder(null);
        numberOfOrders.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numberOfOrdersActionPerformed(evt);
            }
        });

        jSeparator5.setBackground(new java.awt.Color(62, 64, 71));
        jSeparator5.setForeground(new java.awt.Color(62, 64, 71));

        jLabel5.setBackground(new java.awt.Color(36, 49, 60));
        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(62, 64, 71));
        jLabel5.setText("Doctor Name");

        doctorNameEditText.setBackground(new java.awt.Color(242, 242, 242));
        doctorNameEditText.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        doctorNameEditText.setForeground(new java.awt.Color(62, 64, 71));
        doctorNameEditText.setBorder(null);
        doctorNameEditText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                doctorNameEditTextActionPerformed(evt);
            }
        });

        jSeparator6.setBackground(new java.awt.Color(62, 64, 71));
        jSeparator6.setForeground(new java.awt.Color(62, 64, 71));

        javax.swing.GroupLayout addOrderLayout = new javax.swing.GroupLayout(addOrder);
        addOrder.setLayout(addOrderLayout);
        addOrderLayout.setHorizontalGroup(
            addOrderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addOrderLayout.createSequentialGroup()
                .addGroup(addOrderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(addOrderLayout.createSequentialGroup()
                        .addGap(286, 286, 286)
                        .addComponent(jLabel14))
                    .addGroup(addOrderLayout.createSequentialGroup()
                        .addGap(85, 85, 85)
                        .addGroup(addOrderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(numberOfOrders, javax.swing.GroupLayout.DEFAULT_SIZE, 629, Short.MAX_VALUE)
                            .addGroup(addOrderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jSeparator5, javax.swing.GroupLayout.DEFAULT_SIZE, 629, Short.MAX_VALUE)
                                .addComponent(jLabel4)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, addOrderLayout.createSequentialGroup()
                                    .addComponent(jLabel5)
                                    .addGap(536, 536, 536))
                                .addComponent(jSeparator6, javax.swing.GroupLayout.DEFAULT_SIZE, 629, Short.MAX_VALUE)
                                .addComponent(add_btn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(doctorNameEditText)))))
                .addContainerGap(67, Short.MAX_VALUE))
        );
        addOrderLayout.setVerticalGroup(
            addOrderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addOrderLayout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(jLabel14)
                .addGap(39, 39, 39)
                .addComponent(jLabel4)
                .addGap(0, 0, 0)
                .addComponent(numberOfOrders, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 14, Short.MAX_VALUE)
                .addComponent(jLabel5)
                .addGap(12, 12, 12)
                .addComponent(doctorNameEditText, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator6, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(56, 56, 56)
                .addComponent(add_btn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(861, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(addOrder, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(addOrder, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void numberOfOrdersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numberOfOrdersActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_numberOfOrdersActionPerformed

    private void add_btnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_add_btnMouseClicked
        // TODO add your handling code here:
         if (! numberOfOrders.getText().equals("")&&!((Integer.parseInt(numberOfOrders.getText()))<0)&&!(doctorNameEditText.getText().equals(""))){
        int num = Integer.parseInt(numberOfOrders.getText()); 
        String doctor = doctorNameEditText.getText();
        doc_order=new add_doctor_OrderDetails();
        /*new addOrderDetails(num);*/
        
        try {
            
            a.adddocotrOrder(doctor);
            int doc_id = a.todoc_oid(doctor);
            doc_order.setOid(doc_id);
            doc_order.setNumber(num);
            doc_order.setVisible(true);
        doc_order.addRows(num);
            
        } catch (SQLException ex) {
            Logger.getLogger(add_doctor_order.class.getName()).log(Level.SEVERE, null, ex);
        }}else {
             JOptionPane.showMessageDialog(null, "Enter Valid Data");
         }
        
        
       
       
    }//GEN-LAST:event_add_btnMouseClicked

    private void doctorNameEditTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_doctorNameEditTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_doctorNameEditTextActionPerformed
          
    protected void resetPanelData()
    {
        numberOfOrders.setText("");
        
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel addOrder;
    private javax.swing.JPanel add_btn;
    private javax.swing.JTextField doctorNameEditText;
    private javax.swing.JLabel jAddEmployee;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JTextField numberOfOrders;
    // End of variables declaration//GEN-END:variables
}
