/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package final_panels;

import panels.*;
import com.sun.javafx.iio.ios.IosImageLoader;
import java.io.File;
import java.io.IOException;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JTextField;
import hmss_project.admin;
import hmss_project.medicine;
import java.sql.SQLException;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author pc
 */
public class AddMedicine extends javax.swing.JPanel {

    ListMedicines l = null;
    medicine m,n = null;
    admin a= new admin();

    
    /**
     * Creates new form AddEmployee
     */
    
    public AddMedicine() throws SQLException {
        initComponents();
        this.medicineType_comboBox.addItem("Pills");
        this.medicineType_comboBox.addItem("Ointment");
        this.medicineType_comboBox.addItem("Injection");
        this.medicineType_comboBox.addItem("Suppository");
        this.medicineType_comboBox.addItem("Sparay");
        this.medicineType_comboBox.addItem("Syrup");
        
    }

    public medicine returnnn(medicine m)
    {
        return m;
    }
    
    public medicine returnnn22()
    {
        return n;
    }
   
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        adminPanel_addEmployee = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        medicine_companyName_editText = new javax.swing.JTextField();
        jSeparator6 = new javax.swing.JSeparator();
        jLabel14 = new javax.swing.JLabel();
        add_btn = new javax.swing.JPanel();
        jAddEmployee = new javax.swing.JLabel();
        medicineType_comboBox = new javax.swing.JComboBox<>();
        medicine_name_editText = new javax.swing.JTextField();

        adminPanel_addEmployee.setBackground(new java.awt.Color(242, 242, 242));
        adminPanel_addEmployee.setAutoscrolls(true);

        jLabel2.setBackground(new java.awt.Color(36, 49, 60));
        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(62, 64, 71));
        jLabel2.setText("Name");

        jSeparator3.setBackground(new java.awt.Color(62, 64, 71));
        jSeparator3.setForeground(new java.awt.Color(62, 64, 71));

        jLabel10.setBackground(new java.awt.Color(36, 49, 60));
        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(62, 64, 71));
        jLabel10.setText("Type");

        jLabel11.setBackground(new java.awt.Color(36, 49, 60));
        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(62, 64, 71));
        jLabel11.setText("Company");

        medicine_companyName_editText.setBackground(new java.awt.Color(242, 242, 242));
        medicine_companyName_editText.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        medicine_companyName_editText.setForeground(new java.awt.Color(62, 64, 71));
        medicine_companyName_editText.setBorder(null);
        medicine_companyName_editText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                medicine_companyName_editTextActionPerformed(evt);
            }
        });

        jSeparator6.setBackground(new java.awt.Color(62, 64, 71));
        jSeparator6.setForeground(new java.awt.Color(62, 64, 71));

        jLabel14.setBackground(new java.awt.Color(36, 49, 60));
        jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(62, 64, 71));
        jLabel14.setText("Enter Medicine Information");

        add_btn.setBackground(new java.awt.Color(0, 167, 87));
        add_btn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                add_btnMouseClicked(evt);
            }
        });

        jAddEmployee.setBackground(new java.awt.Color(255, 255, 255));
        jAddEmployee.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jAddEmployee.setForeground(new java.awt.Color(255, 255, 255));
        jAddEmployee.setText("ADD");

        javax.swing.GroupLayout add_btnLayout = new javax.swing.GroupLayout(add_btn);
        add_btn.setLayout(add_btnLayout);
        add_btnLayout.setHorizontalGroup(
            add_btnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, add_btnLayout.createSequentialGroup()
                .addContainerGap(50, Short.MAX_VALUE)
                .addComponent(jAddEmployee)
                .addGap(48, 48, 48))
        );
        add_btnLayout.setVerticalGroup(
            add_btnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(add_btnLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jAddEmployee, javax.swing.GroupLayout.DEFAULT_SIZE, 26, Short.MAX_VALUE)
                .addContainerGap())
        );

        medicineType_comboBox.setForeground(new java.awt.Color(62, 64, 71));
        medicineType_comboBox.setMaximumRowCount(20);
        medicineType_comboBox.setBorder(null);

        medicine_name_editText.setBackground(new java.awt.Color(242, 242, 242));
        medicine_name_editText.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        medicine_name_editText.setForeground(new java.awt.Color(62, 64, 71));
        medicine_name_editText.setBorder(null);
        medicine_name_editText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                medicine_name_editTextActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout adminPanel_addEmployeeLayout = new javax.swing.GroupLayout(adminPanel_addEmployee);
        adminPanel_addEmployee.setLayout(adminPanel_addEmployeeLayout);
        adminPanel_addEmployeeLayout.setHorizontalGroup(
            adminPanel_addEmployeeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(adminPanel_addEmployeeLayout.createSequentialGroup()
                .addGap(286, 286, 286)
                .addComponent(jLabel14)
                .addGap(0, 284, Short.MAX_VALUE))
            .addGroup(adminPanel_addEmployeeLayout.createSequentialGroup()
                .addGap(85, 85, 85)
                .addComponent(jLabel2)
                .addContainerGap(680, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, adminPanel_addEmployeeLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(adminPanel_addEmployeeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(add_btn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(adminPanel_addEmployeeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, adminPanel_addEmployeeLayout.createSequentialGroup()
                            .addGap(11, 11, 11)
                            .addGroup(adminPanel_addEmployeeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel11)
                                .addComponent(jLabel10))
                            .addGap(474, 474, 474))
                        .addGroup(adminPanel_addEmployeeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(medicineType_comboBox, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(medicine_companyName_editText, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 598, Short.MAX_VALUE)
                            .addComponent(jSeparator6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 598, Short.MAX_VALUE)))
                    .addGroup(adminPanel_addEmployeeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jSeparator3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 598, Short.MAX_VALUE)
                        .addComponent(medicine_name_editText, javax.swing.GroupLayout.DEFAULT_SIZE, 598, Short.MAX_VALUE)))
                .addGap(132, 132, 132))
        );
        adminPanel_addEmployeeLayout.setVerticalGroup(
            adminPanel_addEmployeeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(adminPanel_addEmployeeLayout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(jLabel14)
                .addGap(26, 26, 26)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(medicine_name_editText, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel10)
                .addGap(18, 18, 18)
                .addComponent(medicineType_comboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addComponent(jLabel11)
                .addGap(12, 12, 12)
                .addComponent(medicine_companyName_editText, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(jSeparator6, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(add_btn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(810, 810, 810))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(adminPanel_addEmployee, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(adminPanel_addEmployee, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void add_btnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_add_btnMouseClicked
        // TODO add your handling code here:
        
        try
        {
            if(!medicine_name_editText.getText().equals("")
                    &&!medicineType_comboBox.getSelectedItem().toString().equals("")&&!medicine_companyName_editText.getText().equals(""))
            {
                medicine m = new medicine();
                m.setMedicineName(medicine_name_editText.getText());
                m.setMedicineType(medicineType_comboBox.getSelectedItem().toString());
                m.setMedicineCompany(medicine_companyName_editText.getText());
                a.addMedicine(m);
                JOptionPane.showMessageDialog(null,"ADDED SUCCESSFULLY !");
                n=returnnn(m);
                
            }
            else
            {
                JOptionPane.showMessageDialog(null,"ENTER THE DATA CLEARLY !");
            }
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null," NOT ADDED !");
        }
        
    }//GEN-LAST:event_add_btnMouseClicked

      
    private void medicine_companyName_editTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_medicine_companyName_editTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_medicine_companyName_editTextActionPerformed

    private void medicine_name_editTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_medicine_name_editTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_medicine_name_editTextActionPerformed
    
    protected void resetPanelData()
    {
        medicine_name_editText.setText("");
        medicine_companyName_editText.setText("");
        
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel add_btn;
    private javax.swing.JPanel adminPanel_addEmployee;
    private javax.swing.JLabel jAddEmployee;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JComboBox<String> medicineType_comboBox;
    private javax.swing.JTextField medicine_companyName_editText;
    private javax.swing.JTextField medicine_name_editText;
    // End of variables declaration//GEN-END:variables
}
