/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package final_panels;

import hmss_project.Vend_med;
import hmss_project.admin;
import hmss_project.orderDetails;
import java.awt.BorderLayout;
import java.awt.Button;
import java.awt.Dimension;
import java.util.ArrayList;
import javax.swing.ComboBoxModel;
import javax.swing.JComboBox;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JTextField;
import javax.swing.border.EmptyBorder;

/**
 *
 * @author hassan
 */
public final class addOrderDetails extends javax.swing.JFrame {
    
    int number;
    int VID;
    
    ArrayList<JLabel> medicineNo = new ArrayList<>();
    ArrayList<JComboBox> medicineName = new ArrayList<>();
    ArrayList<JComboBox> medicineType = new ArrayList<>();
    ArrayList<JTextField> medicineQuantity = new ArrayList<>();
    
    BorderLayout B = new BorderLayout();
    ArrayList<JPanel> row = new ArrayList<>();
    JPanel largePanel = new JPanel();
    
    String m_name,m_type;
    int m_quantity;
    orderDetails od;
    ArrayList<orderDetails> OD = new ArrayList<>();
    
    admin a = new admin();
    Vend_med VM ;

    
    addOrder AO;

    public void setVID(int VID) {
        this.VID = VID;
    }

    public int getVID() {
        return VID;
    }
    
    
    /**
     * Creates new form addOrderDetails
     */
    public addOrderDetails() {
        initComponents();
        setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
    }

    
    public void addRows(int x)
    {
        number = x;
    for(int i=0;i<x;i++)
        {
            medicineNo.add(new JLabel ("M"+" "+String.valueOf(i+1)));
            medicineName.add(new JComboBox());
            medicineType.add(new JComboBox());
            medicineQuantity.add(new JTextField());
            for(int j=0;j<a.ListMedicines().size();j++)
            {
                medicineName.get(i).addItem(a.ListMedicines().get(j).getMedicineName());
                medicineType.get(i).addItem(a.ListMedicines().get(j).getMedicineType());
            }
            medicineName.get(i).setForeground(new java.awt.Color(204,204,204));
            medicineType.get(i).setForeground(new java.awt.Color(204,204,204));
            medicineQuantity.get(i).setForeground(new java.awt.Color(204,204,204));
            
            medicineName.get(i).setPreferredSize(new Dimension(100,30));
            medicineType.get(i).setPreferredSize(new Dimension(100,30));
            medicineQuantity.get(i).setPreferredSize(new Dimension(100,30));
            medicineNo.get(i).setPreferredSize(new Dimension(30,30));
            
            row.add(new JPanel());
            row.get(i).setPreferredSize(new Dimension(450,35));
            
            row.get(i).add(medicineNo.get(i));
            row.get(i).add(medicineName.get(i));
            row.get(i).add(medicineType.get(i));
            row.get(i).add(medicineQuantity.get(i));

            row.get(i).setBackground(new java.awt.Color(204,204,204));
            largePanel.add(row.get(i));
            
        }
        largePanel.setBackground(new java.awt.Color(204,204,204));
        largePanel.setPreferredSize(new Dimension(600, 500));
        largePanel.setBorder(new EmptyBorder(30, 0, 0, 0));
        orderDetailsPanal.setLayout(B);
        orderDetailsPanal.add(largePanel,B.SOUTH);
        
    }
 
    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        orderDetailsPanal = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        save_Btn3 = new javax.swing.JPanel();
        jAddEmployee3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        orderDetailsPanal.setBackground(new java.awt.Color(242, 242, 242));
        orderDetailsPanal.setForeground(new java.awt.Color(153, 0, 153));

        javax.swing.GroupLayout orderDetailsPanalLayout = new javax.swing.GroupLayout(orderDetailsPanal);
        orderDetailsPanal.setLayout(orderDetailsPanalLayout);
        orderDetailsPanalLayout.setHorizontalGroup(
            orderDetailsPanalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 600, Short.MAX_VALUE)
        );
        orderDetailsPanalLayout.setVerticalGroup(
            orderDetailsPanalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 500, Short.MAX_VALUE)
        );

        jPanel2.setBackground(new java.awt.Color(242, 242, 242));

        save_Btn3.setBackground(new java.awt.Color(223, 74, 50));
        save_Btn3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                save_BtnMouseClicked(evt);
            }
        });

        jAddEmployee3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jAddEmployee3.setForeground(new java.awt.Color(204, 204, 204));
        jAddEmployee3.setText("Add order");

        javax.swing.GroupLayout save_Btn3Layout = new javax.swing.GroupLayout(save_Btn3);
        save_Btn3.setLayout(save_Btn3Layout);
        save_Btn3Layout.setHorizontalGroup(
            save_Btn3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(save_Btn3Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jAddEmployee3)
                .addContainerGap(30, Short.MAX_VALUE))
        );
        save_Btn3Layout.setVerticalGroup(
            save_Btn3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(save_Btn3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jAddEmployee3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(234, 234, 234)
                .addComponent(save_Btn3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(31, Short.MAX_VALUE)
                .addComponent(save_Btn3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(orderDetailsPanal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(orderDetailsPanal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void save_BtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_save_BtnMouseClicked
        // TODO add your handling code here:
        AO = new addOrder();
        try
        {
            int x = number;
            for(int i =0; i<number;i++)
            {
                if(!medicineQuantity.get(i).getText().equals("")&&(Integer.parseInt(medicineQuantity.get(i).getText())>0)){
                m_name=medicineName.get(i).getSelectedItem().toString();
                m_type= medicineType.get(i).getSelectedItem().toString();
                m_quantity= Integer.parseInt(medicineQuantity.get(i).getText());
                od=new orderDetails(m_quantity, m_name,this.getVID(), m_type);
                VM = new Vend_med();
                VM.setVID(getVID());
                VM.setMID(a.toMID(m_name));
                VM.setOID(a.getLastOrderID());
                a.insert_Medicine_vend(VM);
                a.addOrderDetails(od);
                x--;
                }else{
                    JOptionPane.showMessageDialog(null, "Enter Valid Quantity");
                    break;
                }
                if(x==0)
                {
                    this.setVisible(false);
                }
            }
            
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null,"Data NOT ADDED !");
        }
    }//GEN-LAST:event_save_BtnMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(addOrderDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(addOrderDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(addOrderDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(addOrderDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new addOrderDetails().setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jAddEmployee3;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel orderDetailsPanal;
    private javax.swing.JPanel save_Btn3;
    // End of variables declaration//GEN-END:variables
}
