/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package final_panels;

import panels.*;
import com.sun.javafx.iio.ios.IosImageLoader;
import java.io.File;
import java.io.IOException;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JTextField;
import hmss_project.admin;
import hmss_project.medicine;
import hmss_project.order;
import hmss_project.orderDetails;
import hmss_project.vendor;
import java.awt.BorderLayout;
import java.awt.Dimension;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.border.EmptyBorder;

/**
 *
 * @author pc
 */
public class addOrder extends javax.swing.JPanel {

    ListMedicines l = null;
    medicine m,n = null;
    addOrderDetails AOD;    
    admin a = new admin();
    order orderr;
    
    ArrayList<orderDetails> orderD = new ArrayList<>();

    public void setOd(ArrayList<orderDetails> od) {
        this.orderD = od;
    }

    public ArrayList<orderDetails> getOd() {
        return orderD;
    }
    
    
    /**
     * Creates new form AddEmployee
     */
    
    public addOrder() {
        initComponents();
        ArrayList<vendor> Vnames = a.ListVendors();
        for(int i = 0;i<Vnames.size();i++)
        {
            vendorNamesCombo.addItem(Vnames.get(i).getVendorName());
        }
        
       
    }
   
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        addOrder = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        numberOfOrders = new javax.swing.JTextField();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel14 = new javax.swing.JLabel();
        add_btn = new javax.swing.JPanel();
        jAddEmployee = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        vendorNamesCombo = new javax.swing.JComboBox<>();

        addOrder.setBackground(new java.awt.Color(242, 242, 242));
        addOrder.setAutoscrolls(true);

        jLabel2.setBackground(new java.awt.Color(36, 49, 60));
        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(192, 59, 43));
        jLabel2.setText("number of orders");

        numberOfOrders.setBackground(new java.awt.Color(242, 242, 242));
        numberOfOrders.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        numberOfOrders.setForeground(new java.awt.Color(62, 64, 71));
        numberOfOrders.setBorder(null);
        numberOfOrders.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numberOfOrdersActionPerformed(evt);
            }
        });

        jSeparator3.setBackground(new java.awt.Color(192, 59, 43));
        jSeparator3.setForeground(new java.awt.Color(192, 59, 43));

        jLabel14.setBackground(new java.awt.Color(36, 49, 60));
        jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(63, 85, 105));
        jLabel14.setText("Enter order Information");

        add_btn.setBackground(new java.awt.Color(36, 49, 60));
        add_btn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                add_btnMouseClicked(evt);
            }
        });

        jAddEmployee.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jAddEmployee.setForeground(new java.awt.Color(204, 204, 204));
        jAddEmployee.setText("ADD");

        javax.swing.GroupLayout add_btnLayout = new javax.swing.GroupLayout(add_btn);
        add_btn.setLayout(add_btnLayout);
        add_btnLayout.setHorizontalGroup(
            add_btnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, add_btnLayout.createSequentialGroup()
                .addContainerGap(50, Short.MAX_VALUE)
                .addComponent(jAddEmployee)
                .addGap(48, 48, 48))
        );
        add_btnLayout.setVerticalGroup(
            add_btnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(add_btnLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jAddEmployee, javax.swing.GroupLayout.DEFAULT_SIZE, 26, Short.MAX_VALUE)
                .addContainerGap())
        );

        jLabel3.setBackground(new java.awt.Color(36, 49, 60));
        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(192, 59, 43));
        jLabel3.setText("Vendor Name");

        javax.swing.GroupLayout addOrderLayout = new javax.swing.GroupLayout(addOrder);
        addOrder.setLayout(addOrderLayout);
        addOrderLayout.setHorizontalGroup(
            addOrderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addOrderLayout.createSequentialGroup()
                .addGroup(addOrderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(addOrderLayout.createSequentialGroup()
                        .addGap(286, 286, 286)
                        .addComponent(jLabel14))
                    .addGroup(addOrderLayout.createSequentialGroup()
                        .addGap(85, 85, 85)
                        .addComponent(jLabel2)))
                .addContainerGap(316, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, addOrderLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(addOrderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, addOrderLayout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(637, 637, 637))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, addOrderLayout.createSequentialGroup()
                        .addGroup(addOrderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jSeparator3)
                            .addComponent(numberOfOrders, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(addOrderLayout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(add_btn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(101, 101, 101))
                    .addGroup(addOrderLayout.createSequentialGroup()
                        .addComponent(vendorNamesCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 629, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );
        addOrderLayout.setVerticalGroup(
            addOrderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addOrderLayout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(jLabel14)
                .addGap(26, 26, 26)
                .addComponent(jLabel2)
                .addGap(12, 12, 12)
                .addComponent(numberOfOrders, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addComponent(vendorNamesCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(56, 56, 56)
                .addComponent(add_btn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(854, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(addOrder, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(addOrder, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void add_btnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_add_btnMouseClicked
        // TODO add your handling code here:
        if (! numberOfOrders.getText().equals("")&&!((Integer.parseInt(numberOfOrders.getText()))<0)){
        try {
            int num = Integer.parseInt(numberOfOrders.getText());
            String vendor = (String) vendorNamesCombo.getSelectedItem();
            int vid = a.toVID(vendor);
            a.addOrder(vid);
            AOD = new addOrderDetails();
            AOD.setVisible(true);
            AOD.addRows(num);
            AOD.setVID(vid);
        } catch (SQLException ex) {
            Logger.getLogger(addOrder.class.getName()).log(Level.SEVERE, null, ex);
        }}else{
            JOptionPane.showMessageDialog(null, "Enter number of order details");
        }
        
        /*new addOrderDetails(num);*/
        
    }//GEN-LAST:event_add_btnMouseClicked
      
    private void numberOfOrdersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numberOfOrdersActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_numberOfOrdersActionPerformed
    
    protected void resetPanelData()
    {
        numberOfOrders.setText("");
        
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel addOrder;
    private javax.swing.JPanel add_btn;
    private javax.swing.JLabel jAddEmployee;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JTextField numberOfOrders;
    private javax.swing.JComboBox<String> vendorNamesCombo;
    // End of variables declaration//GEN-END:variables
}
