/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package final_panels;

import panels.*;
import com.sun.javafx.iio.ios.IosImageLoader;
import hmss_project.Exceptions;
import java.io.File;
import java.io.IOException;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JTextField;
import hmss_project.admin;
import hmss_project.medicine;
import hmss_project.vendor;
import javax.swing.JOptionPane;

/**
 *
 * @author pc
 */
public class AddVendor extends javax.swing.JPanel {

    /**
     * Creates new form AddEmployee
     */
    Exceptions ex = new Exceptions();
    
    public AddVendor() {
        initComponents();
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        addvendor_name = new javax.swing.JPanel();
        vendor_name = new javax.swing.JLabel();
        vendor_name_editText = new javax.swing.JTextField();
        jSeparator3 = new javax.swing.JSeparator();
        vendor_phone = new javax.swing.JLabel();
        vendor_phone_editText = new javax.swing.JTextField();
        jSeparator4 = new javax.swing.JSeparator();
        vendor_address = new javax.swing.JLabel();
        jSeparator5 = new javax.swing.JSeparator();
        vendor_username = new javax.swing.JLabel();
        vendor_username_editText = new javax.swing.JTextField();
        jSeparator6 = new javax.swing.JSeparator();
        jLabel14 = new javax.swing.JLabel();
        add_btn = new javax.swing.JPanel();
        jAddEmployee = new javax.swing.JLabel();
        vendor_address_editText = new javax.swing.JTextField();
        vendor_password_editText = new javax.swing.JTextField();
        jSeparator7 = new javax.swing.JSeparator();
        vendor_password = new javax.swing.JLabel();

        addvendor_name.setBackground(new java.awt.Color(242, 242, 242));
        addvendor_name.setForeground(new java.awt.Color(62, 64, 71));
        addvendor_name.setAutoscrolls(true);

        vendor_name.setBackground(new java.awt.Color(36, 49, 60));
        vendor_name.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        vendor_name.setForeground(new java.awt.Color(62, 64, 71));
        vendor_name.setText("Name");

        vendor_name_editText.setBackground(new java.awt.Color(242, 242, 242));
        vendor_name_editText.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        vendor_name_editText.setForeground(new java.awt.Color(62, 64, 71));
        vendor_name_editText.setBorder(null);
        vendor_name_editText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vendor_name_editTextActionPerformed(evt);
            }
        });

        jSeparator3.setBackground(new java.awt.Color(62, 64, 71));
        jSeparator3.setForeground(new java.awt.Color(62, 64, 71));

        vendor_phone.setBackground(new java.awt.Color(36, 49, 60));
        vendor_phone.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        vendor_phone.setForeground(new java.awt.Color(62, 64, 71));
        vendor_phone.setText("PhoneNo");

        vendor_phone_editText.setBackground(new java.awt.Color(242, 242, 242));
        vendor_phone_editText.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        vendor_phone_editText.setForeground(new java.awt.Color(62, 64, 71));
        vendor_phone_editText.setBorder(null);
        vendor_phone_editText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vendor_phone_editTextActionPerformed(evt);
            }
        });

        jSeparator4.setBackground(new java.awt.Color(62, 64, 71));
        jSeparator4.setForeground(new java.awt.Color(62, 64, 71));

        vendor_address.setBackground(new java.awt.Color(36, 49, 60));
        vendor_address.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        vendor_address.setForeground(new java.awt.Color(62, 64, 71));
        vendor_address.setText("Address");

        jSeparator5.setBackground(new java.awt.Color(62, 64, 71));
        jSeparator5.setForeground(new java.awt.Color(62, 64, 71));

        vendor_username.setBackground(new java.awt.Color(36, 49, 60));
        vendor_username.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        vendor_username.setForeground(new java.awt.Color(62, 64, 71));
        vendor_username.setText("Username");

        vendor_username_editText.setBackground(new java.awt.Color(242, 242, 242));
        vendor_username_editText.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        vendor_username_editText.setForeground(new java.awt.Color(62, 64, 71));
        vendor_username_editText.setBorder(null);
        vendor_username_editText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vendor_username_editTextActionPerformed(evt);
            }
        });

        jSeparator6.setBackground(new java.awt.Color(62, 64, 71));
        jSeparator6.setForeground(new java.awt.Color(62, 64, 71));

        jLabel14.setBackground(new java.awt.Color(36, 49, 60));
        jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(63, 85, 105));
        jLabel14.setText("Enter Vendor Information");

        add_btn.setBackground(new java.awt.Color(0, 167, 87));
        add_btn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                add_btnMouseClicked(evt);
            }
        });

        jAddEmployee.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jAddEmployee.setForeground(new java.awt.Color(204, 204, 204));
        jAddEmployee.setText("ADD");

        javax.swing.GroupLayout add_btnLayout = new javax.swing.GroupLayout(add_btn);
        add_btn.setLayout(add_btnLayout);
        add_btnLayout.setHorizontalGroup(
            add_btnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, add_btnLayout.createSequentialGroup()
                .addContainerGap(50, Short.MAX_VALUE)
                .addComponent(jAddEmployee)
                .addGap(48, 48, 48))
        );
        add_btnLayout.setVerticalGroup(
            add_btnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(add_btnLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jAddEmployee, javax.swing.GroupLayout.DEFAULT_SIZE, 26, Short.MAX_VALUE)
                .addContainerGap())
        );

        vendor_address_editText.setBackground(new java.awt.Color(242, 242, 242));
        vendor_address_editText.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        vendor_address_editText.setForeground(new java.awt.Color(62, 64, 71));
        vendor_address_editText.setBorder(null);
        vendor_address_editText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vendor_address_editTextActionPerformed(evt);
            }
        });

        vendor_password_editText.setBackground(new java.awt.Color(242, 242, 242));
        vendor_password_editText.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        vendor_password_editText.setForeground(new java.awt.Color(62, 64, 71));
        vendor_password_editText.setBorder(null);
        vendor_password_editText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vendor_password_editTextActionPerformed(evt);
            }
        });

        jSeparator7.setBackground(new java.awt.Color(62, 64, 71));
        jSeparator7.setForeground(new java.awt.Color(62, 64, 71));

        vendor_password.setBackground(new java.awt.Color(36, 49, 60));
        vendor_password.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        vendor_password.setForeground(new java.awt.Color(62, 64, 71));
        vendor_password.setText("Password");

        javax.swing.GroupLayout addvendor_nameLayout = new javax.swing.GroupLayout(addvendor_name);
        addvendor_name.setLayout(addvendor_nameLayout);
        addvendor_nameLayout.setHorizontalGroup(
            addvendor_nameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addvendor_nameLayout.createSequentialGroup()
                .addGroup(addvendor_nameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(addvendor_nameLayout.createSequentialGroup()
                        .addGap(0, 80, Short.MAX_VALUE)
                        .addGroup(addvendor_nameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(vendor_username)
                            .addGroup(addvendor_nameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(vendor_address_editText, javax.swing.GroupLayout.PREFERRED_SIZE, 598, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(vendor_username_editText, javax.swing.GroupLayout.PREFERRED_SIZE, 598, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jSeparator6, javax.swing.GroupLayout.PREFERRED_SIZE, 598, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 598, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(addvendor_nameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(vendor_phone_editText, javax.swing.GroupLayout.PREFERRED_SIZE, 598, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jSeparator4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 598, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(addvendor_nameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(vendor_name_editText, javax.swing.GroupLayout.PREFERRED_SIZE, 598, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jSeparator3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 598, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(addvendor_nameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(vendor_password)
                                    .addGroup(addvendor_nameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(vendor_password_editText, javax.swing.GroupLayout.PREFERRED_SIZE, 598, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jSeparator7, javax.swing.GroupLayout.PREFERRED_SIZE, 598, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(add_btn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, addvendor_nameLayout.createSequentialGroup()
                        .addGap(86, 86, 86)
                        .addGroup(addvendor_nameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(vendor_phone, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(vendor_address, javax.swing.GroupLayout.Alignment.LEADING)))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, addvendor_nameLayout.createSequentialGroup()
                        .addGap(85, 85, 85)
                        .addComponent(vendor_name))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, addvendor_nameLayout.createSequentialGroup()
                        .addGap(286, 286, 286)
                        .addComponent(jLabel14)))
                .addContainerGap(127, Short.MAX_VALUE))
        );
        addvendor_nameLayout.setVerticalGroup(
            addvendor_nameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addvendor_nameLayout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(jLabel14)
                .addGap(26, 26, 26)
                .addComponent(vendor_name)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(vendor_name_editText, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(vendor_phone)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(vendor_phone_editText, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 3, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(vendor_address)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(vendor_address_editText, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(7, 7, 7)
                .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(vendor_username)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(vendor_username_editText, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(jSeparator6, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(vendor_password)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(vendor_password_editText, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(jSeparator7, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(add_btn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(704, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(addvendor_name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(addvendor_name, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void add_btnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_add_btnMouseClicked
        // TODO add your handling code here:
        
        try
        {
            if(!vendor_name_editText.getText().equals("")&&!vendor_phone_editText.getText().equals("")
                    &&!vendor_address_editText.getText().equals("")&&!vendor_username_editText.getText().equals(""))
            {
                vendor v=new vendor();
                admin a= new admin();
                
                v.setVendorName(vendor_name_editText.getText());
                v.setVendorAdress(vendor_address_editText.getText());
                v.setPersonUserName(vendor_username_editText.getText());
                v.setPersonPassword(vendor_password_editText.getText());
                v.setPhoneNO(ex.checkPhone(vendor_phone_editText.getText()));
                
                a.addVendor(v);

                JOptionPane.showMessageDialog(null,"ADDED SUCCESSFULLY !");
                
            }
            else
            {
                JOptionPane.showMessageDialog(null,"ENTER THE DATA CLEARLY !");
            }
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null," NOT ADDED !");
        }
        
        

    }//GEN-LAST:event_add_btnMouseClicked

    private void vendor_username_editTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vendor_username_editTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_vendor_username_editTextActionPerformed

    private void vendor_phone_editTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vendor_phone_editTextActionPerformed

    }//GEN-LAST:event_vendor_phone_editTextActionPerformed

    private void vendor_name_editTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vendor_name_editTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_vendor_name_editTextActionPerformed

    private void vendor_address_editTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vendor_address_editTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_vendor_address_editTextActionPerformed

    private void vendor_password_editTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vendor_password_editTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_vendor_password_editTextActionPerformed
    
    protected void resetPanelData()
    {
        vendor_name_editText.setText("");
        vendor_phone_editText.setText("");
        vendor_address_editText.setText("");
        vendor_username_editText.setText("");
        vendor_password_editText.setText("");
        
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel add_btn;
    private javax.swing.JPanel addvendor_name;
    private javax.swing.JLabel jAddEmployee;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JLabel vendor_address;
    private javax.swing.JTextField vendor_address_editText;
    private javax.swing.JLabel vendor_name;
    private javax.swing.JTextField vendor_name_editText;
    private javax.swing.JLabel vendor_password;
    private javax.swing.JTextField vendor_password_editText;
    private javax.swing.JLabel vendor_phone;
    private javax.swing.JTextField vendor_phone_editText;
    private javax.swing.JLabel vendor_username;
    private javax.swing.JTextField vendor_username_editText;
    // End of variables declaration//GEN-END:variables
}
