/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package final_panels;

import com.itextpdf.text.Document;
import com.itextpdf.text.DocumentException;
import com.itextpdf.text.Paragraph;
import com.itextpdf.text.Phrase;
import com.itextpdf.text.pdf.AcroFields;
import com.itextpdf.text.pdf.PdfPCell;
import com.itextpdf.text.pdf.PdfPTable;
import com.itextpdf.text.pdf.PdfReader;
import com.itextpdf.text.pdf.PdfStamper;
import com.itextpdf.text.pdf.PdfWriter;
import static com.sun.org.apache.xalan.internal.lib.ExsltDatetime.date;
import hmss_project.Exceptions;
import hmss_project.admin;
import hmss_project.medicine;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartPanel;
import org.jfree.chart.JFreeChart;
import org.jfree.chart.axis.CategoryAxis;
import org.jfree.chart.axis.CategoryLabelPositions;
import org.jfree.chart.axis.NumberAxis;
import org.jfree.chart.labels.ItemLabelAnchor;
import org.jfree.chart.labels.ItemLabelPosition;
import org.jfree.chart.labels.StandardCategoryItemLabelGenerator;
import org.jfree.chart.plot.CategoryPlot;
import org.jfree.chart.plot.PlotOrientation;
import org.jfree.chart.renderer.category.CategoryItemRenderer;
import org.jfree.data.category.CategoryDataset;
import org.jfree.data.category.DefaultCategoryDataset;
import org.jfree.ui.*;
import org.jfree.ui.*;
import java.awt.BasicStroke;
import java.awt.Color;
import java.awt.Font;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.IOException;
import static javafx.scene.paint.Color.color;
import static javafx.scene.paint.Color.color;
import javax.swing.BorderFactory;
import javax.swing.JFrame;
import javax.swing.SwingUtilities;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartFrame;
import org.jfree.chart.ChartPanel;
import org.jfree.chart.JFreeChart;
import org.jfree.chart.block.BlockBorder;
import org.jfree.chart.plot.PlotOrientation;
import org.jfree.chart.plot.XYPlot;
import org.jfree.chart.renderer.xy.XYLineAndShapeRenderer;
import org.jfree.chart.title.TextTitle;
import org.jfree.data.xy.XYDataset;
import org.jfree.data.xy.XYSeries;
import org.jfree.data.xy.XYSeriesCollection;

/**
 *
 * @author hassan
 */
public class Listvendor_lowestprice extends javax.swing.JPanel {

    admin a = new admin();
    Exceptions e = new Exceptions();
    
    
    
    /**
     * Creates new form searchEmployee
     */
    public Listvendor_lowestprice() {
        initComponents();
        Search_error.setText(" ");
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        vendor_name = new javax.swing.JPanel();
        MedicineName = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        Price = new javax.swing.JTextField();
        jSeparator4 = new javax.swing.JSeparator();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel44 = new javax.swing.JLabel();
        vendor_id = new javax.swing.JTextField();
        jSeparator16 = new javax.swing.JSeparator();
        update_btn = new javax.swing.JPanel();
        jLabel45 = new javax.swing.JLabel();
        search_btn = new javax.swing.JPanel();
        jLabel46 = new javax.swing.JLabel();
        Search_error = new javax.swing.JLabel();
        jSeparator6 = new javax.swing.JSeparator();
        jLabel5 = new javax.swing.JLabel();
        Vedname = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        jLabel47 = new javax.swing.JLabel();

        vendor_name.setBackground(new java.awt.Color(242, 242, 242));
        vendor_name.setForeground(new java.awt.Color(62, 64, 71));
        vendor_name.setAutoscrolls(true);

        MedicineName.setBackground(new java.awt.Color(204, 204, 204));
        MedicineName.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        MedicineName.setForeground(new java.awt.Color(62, 64, 71));
        MedicineName.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(63, 85, 105)));
        MedicineName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MedicineNameActionPerformed(evt);
            }
        });

        jLabel3.setBackground(new java.awt.Color(36, 49, 60));
        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(62, 64, 71));
        jLabel3.setText("Name");

        Price.setBackground(new java.awt.Color(242, 242, 242));
        Price.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Price.setForeground(new java.awt.Color(36, 49, 60));
        Price.setBorder(null);

        jSeparator4.setBackground(new java.awt.Color(62, 64, 71));
        jSeparator4.setForeground(new java.awt.Color(62, 64, 71));

        jLabel14.setBackground(new java.awt.Color(36, 49, 60));
        jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(63, 85, 105));
        jLabel14.setText("Search for lowest price  ");

        jLabel15.setBackground(new java.awt.Color(36, 49, 60));
        jLabel15.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(26, 177, 136));

        jLabel6.setBackground(new java.awt.Color(36, 49, 60));
        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(62, 64, 71));
        jLabel6.setText("VENDOR_ID");

        jLabel44.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/icons8_Contacts_25px_1.png"))); // NOI18N

        vendor_id.setBackground(new java.awt.Color(242, 242, 242));
        vendor_id.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        vendor_id.setForeground(new java.awt.Color(36, 49, 60));
        vendor_id.setBorder(null);

        jSeparator16.setBackground(new java.awt.Color(62, 64, 71));
        jSeparator16.setForeground(new java.awt.Color(62, 64, 71));

        update_btn.setBackground(new java.awt.Color(36, 49, 60));
        update_btn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                update_btnMouseClicked(evt);
            }
        });

        jLabel45.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel45.setForeground(new java.awt.Color(204, 204, 204));
        jLabel45.setText("Report");

        javax.swing.GroupLayout update_btnLayout = new javax.swing.GroupLayout(update_btn);
        update_btn.setLayout(update_btnLayout);
        update_btnLayout.setHorizontalGroup(
            update_btnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(update_btnLayout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addComponent(jLabel45)
                .addContainerGap(51, Short.MAX_VALUE))
        );
        update_btnLayout.setVerticalGroup(
            update_btnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(update_btnLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel45, javax.swing.GroupLayout.DEFAULT_SIZE, 26, Short.MAX_VALUE)
                .addContainerGap())
        );

        search_btn.setBackground(new java.awt.Color(223, 74, 50));
        search_btn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                search_btnMouseClicked(evt);
            }
        });

        jLabel46.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel46.setForeground(new java.awt.Color(204, 204, 204));
        jLabel46.setText("Search");

        javax.swing.GroupLayout search_btnLayout = new javax.swing.GroupLayout(search_btn);
        search_btn.setLayout(search_btnLayout);
        search_btnLayout.setHorizontalGroup(
            search_btnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(search_btnLayout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addComponent(jLabel46)
                .addContainerGap(47, Short.MAX_VALUE))
        );
        search_btnLayout.setVerticalGroup(
            search_btnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(search_btnLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel46, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        Search_error.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Search_error.setForeground(new java.awt.Color(153, 0, 0));
        Search_error.setText("Search");

        jSeparator6.setBackground(new java.awt.Color(62, 64, 71));
        jSeparator6.setForeground(new java.awt.Color(62, 64, 71));

        jLabel5.setBackground(new java.awt.Color(36, 49, 60));
        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(62, 64, 71));
        jLabel5.setText("Price");

        Vedname.setBackground(new java.awt.Color(242, 242, 242));
        Vedname.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Vedname.setForeground(new java.awt.Color(36, 49, 60));
        Vedname.setBorder(null);

        jLabel19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/icons8_Money_25px.png"))); // NOI18N

        jLabel47.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/icons8_Contacts_25px_1.png"))); // NOI18N

        javax.swing.GroupLayout vendor_nameLayout = new javax.swing.GroupLayout(vendor_name);
        vendor_name.setLayout(vendor_nameLayout);
        vendor_nameLayout.setHorizontalGroup(
            vendor_nameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(vendor_nameLayout.createSequentialGroup()
                .addGap(320, 320, 320)
                .addComponent(jLabel14)
                .addGap(0, 281, Short.MAX_VALUE))
            .addGroup(vendor_nameLayout.createSequentialGroup()
                .addGap(85, 85, 85)
                .addGroup(vendor_nameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(vendor_nameLayout.createSequentialGroup()
                        .addGroup(vendor_nameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, vendor_nameLayout.createSequentialGroup()
                                .addComponent(Search_error)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(search_btn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(vendor_nameLayout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(jLabel47)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(vendor_id))
                            .addComponent(jSeparator4)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, vendor_nameLayout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(jLabel19)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Price))
                            .addComponent(jSeparator16)
                            .addComponent(MedicineName)
                            .addComponent(jSeparator6)
                            .addGroup(vendor_nameLayout.createSequentialGroup()
                                .addComponent(jLabel44)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Vedname)))
                        .addGap(85, 85, 85))
                    .addGroup(vendor_nameLayout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(vendor_nameLayout.createSequentialGroup()
                        .addGroup(vendor_nameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel6)
                            .addComponent(jLabel15))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, vendor_nameLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(update_btn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(325, 325, 325))
        );
        vendor_nameLayout.setVerticalGroup(
            vendor_nameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(vendor_nameLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel14)
                .addGap(18, 18, 18)
                .addGroup(vendor_nameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(vendor_nameLayout.createSequentialGroup()
                        .addComponent(MedicineName, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(vendor_nameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(vendor_nameLayout.createSequentialGroup()
                                .addComponent(Search_error)
                                .addGap(88, 88, 88)
                                .addComponent(jLabel6)
                                .addGap(12, 12, 12)
                                .addGroup(vendor_nameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(vendor_id, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel47))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jSeparator16, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel5)
                                .addGap(9, 9, 9)
                                .addGroup(vendor_nameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(Price, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel19))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(search_btn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Vedname, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel44))
                .addGap(12, 12, 12)
                .addComponent(jSeparator6, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(update_btn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16)
                .addComponent(jLabel15)
                .addContainerGap(666, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(vendor_name, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(vendor_name, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void search_btnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_search_btnMouseClicked
        try {
            // TODO add your handling code here:
            admin ad= new admin();
            float x=ad.viewLowPrice(MedicineName.getText());
            int b = ad.viewvedid(MedicineName.getText());

            vendor_id.setText(""+b);
            String vd_name=ad.toVName(b);
            Price.setText(""+x);
            Vedname.setText(vd_name);
        } catch (SQLException ex) {
            Logger.getLogger(Listvendor_lowestprice.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_search_btnMouseClicked

    private void update_btnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_update_btnMouseClicked
        // TODO add your handling code here:
        admin ad=new admin();
        String name= Vedname.getText();

        String id=vendor_id.getText();
        String vnd_price=Price.getText();
        DefaultCategoryDataset dataset=new DefaultCategoryDataset();
        dataset.setValue(new Double(vnd_price), "Lowest price", vnd_price);
        dataset.setValue(new Double(vnd_price), "Lowest price", vnd_price);

        JFreeChart chart =ChartFactory.createBarChart3D("LowestPrice", "price", "price", dataset, PlotOrientation.VERTICAL, true, true, true);
        chart.setBackgroundPaint(Color.white);
        chart.getTitle().setPaint(Color.red);
        CategoryPlot p=chart.getCategoryPlot();
        p.setRangeGridlinePaint(Color.BLUE);
        ChartFrame frame=new ChartFrame("bar chart for lowest price",chart);
        frame.setVisible(true);
        frame.setSize(450,350);

        String file_name="C:\\Users\\hassan\\Documents\\NetBeansProjects\\Hassan_SWE2_2\\reports\\finalreport.pdf";
        Document doc=new Document();
        try {
            PdfWriter.getInstance(doc,new FileOutputStream(file_name) );
        } catch (FileNotFoundException ex) {
            Logger.getLogger(admin.class.getName()).log(Level.SEVERE, null, ex);
        } catch (DocumentException ex) {
            Logger.getLogger(Listvendor_lowestprice.class.getName()).log(Level.SEVERE, null, ex);
        }

        doc.open();

        PdfPTable table =new PdfPTable(3);
        PdfPCell c1=new PdfPCell(new  Phrase("ID"));
        table.addCell(c1);

        c1=new PdfPCell(new  Phrase("name"));
        table.addCell(c1);

        c1=new PdfPCell(new  Phrase("price"));
        table.addCell(c1);
        table.setHeaderRows(1);
        table.addCell(id);
        table.addCell(name);
        table.addCell(vnd_price);
        try {
            doc.add(table);
        } catch (DocumentException ex) {
            Logger.getLogger(Listvendor_lowestprice.class.getName()).log(Level.SEVERE, null, ex);
        }
        System.out.print("finished");

        doc.close();

    }//GEN-LAST:event_update_btnMouseClicked

    private void MedicineNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MedicineNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MedicineNameActionPerformed
      
    protected void resetPanelData()
    {
        MedicineName.setText("");
        vendor_id.setText("");
      
       
       
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField MedicineName;
    private javax.swing.JTextField Price;
    private javax.swing.JLabel Search_error;
    private javax.swing.JTextField Vedname;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JSeparator jSeparator16;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JPanel search_btn;
    private javax.swing.JPanel update_btn;
    private javax.swing.JTextField vendor_id;
    private javax.swing.JPanel vendor_name;
    // End of variables declaration//GEN-END:variables
}
