/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package final_panels;

import hmss_project.Exceptions;
import hmss_project.admin;
import hmss_project.medicine;
import hmss_project.vendor;


/**
 *
 * @author hassan
 */
public class SearchVendor extends javax.swing.JPanel {
    admin a = new admin();
    Exceptions e = new Exceptions();
    
    /**
     * Creates new form searchEmployee
     */
    public SearchVendor() {
        initComponents();
        Search_error.setText(" ");
        update_error.setText(" ");
        Delete_error.setText(" ");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        adminPanel_addEmployee = new javax.swing.JPanel();
        VendorSearch_editText = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jSeparator4 = new javax.swing.JSeparator();
        jLabel10 = new javax.swing.JLabel();
        jSeparator5 = new javax.swing.JSeparator();
        jLabel11 = new javax.swing.JLabel();
        jSeparator6 = new javax.swing.JSeparator();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        delete_btn = new javax.swing.JPanel();
        jLabel28 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jSeparator16 = new javax.swing.JSeparator();
        update_btn = new javax.swing.JPanel();
        jLabel45 = new javax.swing.JLabel();
        search_btn = new javax.swing.JPanel();
        jLabel46 = new javax.swing.JLabel();
        Search_error = new javax.swing.JLabel();
        update_error = new javax.swing.JLabel();
        Delete_error = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jSeparator7 = new javax.swing.JSeparator();
        update_vendorpassword_editText1 = new javax.swing.JTextField();
        update_vendorPhone_editText = new javax.swing.JTextField();
        update_vendoraddress_editText = new javax.swing.JTextField();
        update_vendorusername_editText = new javax.swing.JTextField();
        update_vendorName_editText = new javax.swing.JTextField();

        adminPanel_addEmployee.setBackground(new java.awt.Color(242, 242, 242));
        adminPanel_addEmployee.setAutoscrolls(true);

        VendorSearch_editText.setBackground(new java.awt.Color(204, 204, 204));
        VendorSearch_editText.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        VendorSearch_editText.setForeground(new java.awt.Color(62, 64, 71));
        VendorSearch_editText.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(63, 85, 105)));
        VendorSearch_editText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VendorSearch_editTextActionPerformed(evt);
            }
        });

        jLabel3.setBackground(new java.awt.Color(36, 49, 60));
        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(26, 177, 136));
        jLabel3.setText("Address");

        jSeparator4.setBackground(new java.awt.Color(26, 177, 136));
        jSeparator4.setForeground(new java.awt.Color(26, 177, 136));

        jLabel10.setBackground(new java.awt.Color(36, 49, 60));
        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(26, 177, 136));
        jLabel10.setText("phoneNO");

        jSeparator5.setBackground(new java.awt.Color(26, 177, 136));
        jSeparator5.setForeground(new java.awt.Color(26, 177, 136));

        jLabel11.setBackground(new java.awt.Color(36, 49, 60));
        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(26, 177, 136));
        jLabel11.setText("Username");

        jSeparator6.setBackground(new java.awt.Color(26, 177, 136));
        jSeparator6.setForeground(new java.awt.Color(26, 177, 136));

        jLabel14.setBackground(new java.awt.Color(36, 49, 60));
        jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(63, 85, 105));
        jLabel14.setText("Search for Vendor");

        jLabel15.setBackground(new java.awt.Color(36, 49, 60));
        jLabel15.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(26, 177, 136));

        delete_btn.setBackground(new java.awt.Color(223, 74, 50));
        delete_btn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                delete_btnMouseClicked(evt);
            }
        });

        jLabel28.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel28.setForeground(new java.awt.Color(204, 204, 204));
        jLabel28.setText("Delete");

        javax.swing.GroupLayout delete_btnLayout = new javax.swing.GroupLayout(delete_btn);
        delete_btn.setLayout(delete_btnLayout);
        delete_btnLayout.setHorizontalGroup(
            delete_btnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(delete_btnLayout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addComponent(jLabel28)
                .addContainerGap(51, Short.MAX_VALUE))
        );
        delete_btnLayout.setVerticalGroup(
            delete_btnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(delete_btnLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel28, javax.swing.GroupLayout.DEFAULT_SIZE, 26, Short.MAX_VALUE)
                .addContainerGap())
        );

        jLabel6.setBackground(new java.awt.Color(36, 49, 60));
        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(26, 177, 136));
        jLabel6.setText("Name");

        jSeparator16.setBackground(new java.awt.Color(26, 177, 136));
        jSeparator16.setForeground(new java.awt.Color(26, 177, 136));

        update_btn.setBackground(new java.awt.Color(0, 167, 87));
        update_btn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                update_btnMouseClicked(evt);
            }
        });

        jLabel45.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel45.setForeground(new java.awt.Color(204, 204, 204));
        jLabel45.setText("Update");

        javax.swing.GroupLayout update_btnLayout = new javax.swing.GroupLayout(update_btn);
        update_btn.setLayout(update_btnLayout);
        update_btnLayout.setHorizontalGroup(
            update_btnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(update_btnLayout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addComponent(jLabel45)
                .addContainerGap(51, Short.MAX_VALUE))
        );
        update_btnLayout.setVerticalGroup(
            update_btnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(update_btnLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel45, javax.swing.GroupLayout.DEFAULT_SIZE, 26, Short.MAX_VALUE)
                .addContainerGap())
        );

        search_btn.setBackground(new java.awt.Color(223, 74, 50));
        search_btn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                search_btnMouseClicked(evt);
            }
        });

        jLabel46.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel46.setForeground(new java.awt.Color(255, 255, 255));
        jLabel46.setText("Search");

        javax.swing.GroupLayout search_btnLayout = new javax.swing.GroupLayout(search_btn);
        search_btn.setLayout(search_btnLayout);
        search_btnLayout.setHorizontalGroup(
            search_btnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(search_btnLayout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addComponent(jLabel46)
                .addContainerGap(47, Short.MAX_VALUE))
        );
        search_btnLayout.setVerticalGroup(
            search_btnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(search_btnLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel46, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        Search_error.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Search_error.setForeground(new java.awt.Color(153, 0, 0));
        Search_error.setText("Search");

        update_error.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        update_error.setForeground(new java.awt.Color(153, 0, 0));
        update_error.setText("Update");

        Delete_error.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Delete_error.setForeground(new java.awt.Color(153, 0, 0));
        Delete_error.setText("Delete");

        jLabel12.setBackground(new java.awt.Color(36, 49, 60));
        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(26, 177, 136));
        jLabel12.setText("Password");

        jSeparator7.setBackground(new java.awt.Color(26, 177, 136));
        jSeparator7.setForeground(new java.awt.Color(26, 177, 136));

        update_vendorpassword_editText1.setBackground(new java.awt.Color(242, 242, 242));
        update_vendorpassword_editText1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        update_vendorpassword_editText1.setForeground(new java.awt.Color(62, 64, 71));
        update_vendorpassword_editText1.setBorder(null);

        update_vendorPhone_editText.setBackground(new java.awt.Color(242, 242, 242));
        update_vendorPhone_editText.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        update_vendorPhone_editText.setForeground(new java.awt.Color(62, 64, 71));
        update_vendorPhone_editText.setBorder(null);

        update_vendoraddress_editText.setBackground(new java.awt.Color(242, 242, 242));
        update_vendoraddress_editText.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        update_vendoraddress_editText.setForeground(new java.awt.Color(62, 64, 71));
        update_vendoraddress_editText.setBorder(null);

        update_vendorusername_editText.setBackground(new java.awt.Color(242, 242, 242));
        update_vendorusername_editText.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        update_vendorusername_editText.setForeground(new java.awt.Color(62, 64, 71));
        update_vendorusername_editText.setBorder(null);

        update_vendorName_editText.setBackground(new java.awt.Color(242, 242, 242));
        update_vendorName_editText.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        update_vendorName_editText.setForeground(new java.awt.Color(62, 64, 71));
        update_vendorName_editText.setBorder(null);

        javax.swing.GroupLayout adminPanel_addEmployeeLayout = new javax.swing.GroupLayout(adminPanel_addEmployee);
        adminPanel_addEmployee.setLayout(adminPanel_addEmployeeLayout);
        adminPanel_addEmployeeLayout.setHorizontalGroup(
            adminPanel_addEmployeeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(adminPanel_addEmployeeLayout.createSequentialGroup()
                .addGap(139, 139, 139)
                .addComponent(update_error)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Delete_error)
                .addGap(96, 96, 96))
            .addGroup(adminPanel_addEmployeeLayout.createSequentialGroup()
                .addGap(85, 85, 85)
                .addGroup(adminPanel_addEmployeeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(adminPanel_addEmployeeLayout.createSequentialGroup()
                        .addComponent(update_btn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(delete_btn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(55, 55, 55))
                    .addGroup(adminPanel_addEmployeeLayout.createSequentialGroup()
                        .addGroup(adminPanel_addEmployeeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel12)
                            .addComponent(jLabel3)
                            .addComponent(jLabel11)
                            .addComponent(jLabel10)
                            .addComponent(jLabel6)
                            .addComponent(Search_error)
                            .addComponent(jLabel15)
                            .addGroup(adminPanel_addEmployeeLayout.createSequentialGroup()
                                .addGap(235, 235, 235)
                                .addComponent(jLabel14)))
                        .addContainerGap(331, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, adminPanel_addEmployeeLayout.createSequentialGroup()
                        .addGroup(adminPanel_addEmployeeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(update_vendorusername_editText, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(update_vendorName_editText, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(update_vendoraddress_editText, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(update_vendorPhone_editText, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparator4, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparator5, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparator6)
                            .addComponent(jSeparator16, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(VendorSearch_editText, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(adminPanel_addEmployeeLayout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(search_btn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jSeparator7, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(update_vendorpassword_editText1))
                        .addGap(85, 85, 85))))
        );
        adminPanel_addEmployeeLayout.setVerticalGroup(
            adminPanel_addEmployeeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(adminPanel_addEmployeeLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel14)
                .addGap(18, 18, 18)
                .addComponent(VendorSearch_editText, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Search_error)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(search_btn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addComponent(jLabel6)
                .addGap(7, 7, 7)
                .addComponent(update_vendorName_editText, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator16, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3)
                .addGap(12, 12, 12)
                .addComponent(update_vendoraddress_editText, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel10)
                .addGap(12, 12, 12)
                .addComponent(update_vendorPhone_editText, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(update_vendorusername_editText, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(7, 7, 7)
                .addComponent(jSeparator6, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jLabel15)
                .addGap(18, 18, 18)
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(update_vendorpassword_editText1, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(7, 7, 7)
                .addComponent(jSeparator7, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(74, 74, 74)
                .addGroup(adminPanel_addEmployeeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(delete_btn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(update_btn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(adminPanel_addEmployeeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(update_error)
                    .addComponent(Delete_error))
                .addContainerGap(447, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 805, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(adminPanel_addEmployee, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1218, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(adminPanel_addEmployee, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void VendorSearch_editTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VendorSearch_editTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_VendorSearch_editTextActionPerformed

    private void search_btnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_search_btnMouseClicked
        // TODO add your handling code here:
        try
            {if(VendorSearch_editText.getText().equals(""))
            {
                Search_error.setText("enter medicine name !");
            }
            else
            {

                vendor v= a.searchVendor(VendorSearch_editText.getText());
                update_vendorName_editText.setText(v.getVendorName());
                update_vendoraddress_editText.setText(v.getVendorAdress());
                update_vendorPhone_editText.setText(v.getPhoneNO()+"");
                update_vendorusername_editText.setText(v.getPersonUserName());
                update_vendorpassword_editText1.setText(v.getPersonPassword());
                Search_error.setText("SEARCH SUCCEEDED");
            }
        }
        catch(Exception e)
        {
            Search_error.setText("UNABLE TO SESRCH FOR MEDICINE !");
        }
        
    }//GEN-LAST:event_search_btnMouseClicked

    private void update_btnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_update_btnMouseClicked
 // TODO add your handling code here:
        
        try
        {
            vendor v=new vendor();
            if(update_vendorName_editText.getText().equals("")||update_vendoraddress_editText.getText().equals("")
                    ||update_vendorPhone_editText.getText().equals("")||update_vendorusername_editText.getText().equals(""))
            {
                update_error.setText("please fill the empty places !");
            }
            else
               
                v.setVendorName(update_vendorName_editText.getText());
                v.setVendorAdress(update_vendoraddress_editText.getText());
                v.setPhoneNO(Integer.parseInt(update_vendorPhone_editText.getText()));
                v.setPersonUserName(update_vendorusername_editText.getText());
                v.setPersonPassword(update_vendorpassword_editText1.getText());
                a.updateVendor(v,VendorSearch_editText.getText());
                 update_error.setText("MEDICINE UPDATED SUCCESSFULLY !");
                resetPanelData();
        }
        catch(Exception e)
        {
            update_error.setText("UNABLE TO UPDATE MEDICINE !");
        }
 
    }//GEN-LAST:event_update_btnMouseClicked

    private void delete_btnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_delete_btnMouseClicked
 // TODO add your handling code here:
        try{
            
            if(update_vendorName_editText.getText().equals(""))
            {
                Delete_error.setText("enter medicine name !");
            }
            else
            {
                a.deleteVendor(update_vendorName_editText.getText());
                Delete_error.setText("DELETED SUCCESSFULLY");
                resetPanelData();
            }

        }
        catch(Exception e)
        {
            Delete_error.setText("UNABLE TO DELETE MEDICINE !");
        }
            }//GEN-LAST:event_delete_btnMouseClicked
      
    protected void resetPanelData()
    {
        VendorSearch_editText.setText("");
        update_vendorName_editText.setText("");
        update_vendoraddress_editText.setText("");
        update_vendorPhone_editText.setText("");
        update_vendorusername_editText.setText("");
        update_vendorpassword_editText1.setText("");
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Delete_error;
    private javax.swing.JLabel Search_error;
    private javax.swing.JTextField VendorSearch_editText;
    private javax.swing.JPanel adminPanel_addEmployee;
    private javax.swing.JPanel delete_btn;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JSeparator jSeparator16;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JPanel search_btn;
    private javax.swing.JPanel update_btn;
    private javax.swing.JLabel update_error;
    private javax.swing.JTextField update_vendorName_editText;
    private javax.swing.JTextField update_vendorPhone_editText;
    private javax.swing.JTextField update_vendoraddress_editText;
    private javax.swing.JTextField update_vendorpassword_editText1;
    private javax.swing.JTextField update_vendorusername_editText;
    // End of variables declaration//GEN-END:variables
}
